from pathlib import Path
import json,re,shutil
p=Path('presentations/the-licence-and-the-shared-name');r=p/'review-revision'
for f in ['art.mjs','work/scenes.json','work/editorial.json','work/voice-receipts.json']:
 d=r/'before'/f;d.parent.mkdir(parents=True,exist_ok=True)
 if not d.exists():shutil.copy2(p/f,d)
ss=json.loads((r/'before/work/scenes.json').read_text());ss[3]['lines'][2]='A departing team could keep developing released open-source code while ceasing official mark use.'
refs=[[1,2,54,56,69],[15,16,25,26,32,33,45,46,47,69],[54,56,62,63],[1,6,54,56,63,68,69]]
purposes=['Locate the book at the separation between software freedom and the economic/public name surrounding it.','Show that copying covered code does not copy a customer relationship or clear unrelated data and model rights.','Explain a modular proposal separating technical permissions from voluntary common-name duties and bounded custody.','Make ordinary exit intelligible through continued covered code work, factual history and a distinct active name.']
for i,s in enumerate(ss):
 s['sources']=refs[i];s['emotionalPlan']['purpose']=purposes[i];s['emotionalPlan']['visualActing']='Follow one fictional software team and code F; copying, inspecting rights and changing active signage are distinct actions. Curiosity becomes concern at hidden obligations, then careful continued work. No legal approval or automatic customer/certification transfer.'
(p/'work/scenes.json').write_text(json.dumps(ss,indent=2)+'\n');ed=json.loads((r/'before/work/editorial.json').read_text());sections=json.loads((p/'source/sections.json').read_text());b=(p/'source/source.txt').read_text().encode('utf-16-le');ed['claims']=[{'id':'claim-'+s['id'],'statement':' '.join(s['lines']),'kind':'source-claim','noveltyScope':'within-source','spans':[{'sourceId':sections[k]['id'],'start':sections[k]['start'],'end':sections[k]['end'],'quote':b[sections[k]['start']*2:sections[k]['end']*2].decode('utf-16-le')}for k in s['sources']]}for s in ss];ed['scenePlan']=[{'id':s['id'],'lens':s['lens'],'purpose':purposes[i],'emotionalPlan':s['emotionalPlan']}for i,s in enumerate(ss)];ed['narrativeFramework']['how']='Follow the historical rights gap, inspect the proposed modular compact, and examine ordinary exit where covered open-source code and factual history remain but current common-name use ceases.';ed['originalIllustrations']=[{'id':'software-team-F','status':'Original fictional software studio and code F. Schematic interface/code, no real licence/copyright compatibility claim or source-reported organization. Copying covered code does not convey unrelated data, customers or current certification. The folio has illustrative partial legal functions, not a complete seven-instrument implementation.','sourceBasis':['source-54','source-56']},{'id':'ordinary-exit','status':'Source-supported ordinary departure illustrated with retained code F and factual history, different active sign. No contested custodian succession, general right to seize a mark, ongoing current certification or verified enforceability.','sourceBasis':['source-63']}];ed['sourceImageReview']={'count':24,'selectedForConceptualAdaptation':['page-0091-image-01.png:Figure16 separates technical commons and shared name','page-0113-image-01.png:Figure21 ordinary exit and portable evidence','page-0065-image-01.png/page-0078-image-01.png/page-0081-image-01.png:rights layers'], 'decision':'All24 source images inspected; dense charts not embedded. Adapt the distinctions into a coherent software studio, rights folio and active-name change. Cover elephant omitted.'};ed['review']={'scriptApproved':True,'reviewer':'root','sourceScope':'Fresh complete1/2/33/45/46/47/54/55/56/62/63/68/69; chapter-aligned opening extracts5/6/10/15/18/22/25/28/32/35/38/42/50/58/65/66 and full heading map.24images inspected. No fresh every-word read, bibliography or current legal validation claimed. Root read proposed20lines and source63 passages; not root fullsection review.'};(p/'work/editorial.json').write_text(json.dumps(ed,indent=2)+'\n');d=json.loads((r/'progress.json').read_text());d.update(status='approved-production',scriptApproved=True);(r/'progress.json').write_text(json.dumps(d,indent=2)+'\n')
