from pathlib import Path
import json,sys
sys.path.insert(0,'tools')
from build_books import keyword_identifier
w=Path(__file__).parent;r=json.loads((w/'release.json').read_text());codes=['en','fr','de','es','pt','it','ro','pl']
titles=['The Society That Selects Us','La société qui nous sélectionne','Die Gesellschaft, die uns selektiert','La sociedad que nos selecciona','A sociedade que nos seleciona','La società che ci seleziona','Societatea care ne selectează','Społeczeństwo, które nas selekcjonuje']
subs=['Fertility, Personality, and the Human Futures We Build Without Realizing It','Fécondité, personnalité et futurs humains que nous construisons sans le savoir','Fertilität, Persönlichkeit und die menschlichen Zukünfte, die wir unbemerkt gestalten','Fertilidad, personalidad y los futuros humanos que construimos sin darnos cuenta','Fertilidade, personalidade e os futuros humanos que construímos sem perceber','Fertilità, personalità e i futuri umani che costruiamo senza accorgercene','Fertilitate, personalitate și viitorurile umane pe care le construim fără să ne dăm seama','Dzietność, osobowość i ludzkie przyszłości, które budujemy, nie zdając sobie z tego sprawy']
desc=[
'How do institutions influence who can turn the desire for children into family life? This scientific and philosophical essay examines fertility, personality and social environments. It distinguishes genetic selection, cultural change, social filtering and demographic shifts. Chapters compare urban living, kinship networks and the difficulties of measuring personality across cultures. Four future scenarios explore tensions between belonging, autonomy and algorithmic mediation. An evidence map separates established findings from hypotheses that still need testing.',
'Comment les institutions influencent-elles la possibilité de transformer le désir d’enfants en vie familiale ? Cet essai scientifique et philosophique examine la fécondité, la personnalité et les milieux sociaux. Il distingue sélection génétique, changement culturel, filtrage social et transformations démographiques. Les chapitres comparent vie urbaine, réseaux de parenté et difficultés de mesure interculturelle de la personnalité. Quatre scénarios futurs explorent les tensions entre appartenance, autonomie et médiation algorithmique. Une carte des preuves sépare les résultats établis des hypothèses restant à tester.',
'Wie beeinflussen Institutionen, wer einen Kinderwunsch in Familienleben umsetzen kann? Dieser wissenschaftliche und philosophische Essay untersucht Fertilität, Persönlichkeit und soziale Lebensbedingungen. Er unterscheidet genetische Selektion, kulturellen Wandel, soziale Filterung und demografische Verschiebungen. Die Kapitel vergleichen Stadtleben, Verwandtschaftsnetze und die Schwierigkeiten kulturübergreifender Persönlichkeitsmessung. Vier Zukunftsszenarien erkunden Spannungen zwischen Zugehörigkeit, Autonomie und algorithmischer Vermittlung. Eine Evidenzübersicht trennt gesicherte Befunde von noch zu prüfenden Hypothesen.',
'¿Cómo influyen las instituciones en quién puede convertir el deseo de tener hijos en una vida familiar? Este ensayo científico y filosófico examina la fertilidad, la personalidad y los entornos sociales. Distingue selección genética, cambio cultural, filtrado social y transformaciones demográficas. Los capítulos comparan vida urbana, redes de parentesco y dificultades de medir la personalidad entre culturas. Cuatro escenarios futuros exploran tensiones entre pertenencia, autonomía y mediación algorítmica. Un mapa de evidencias separa los resultados establecidos de las hipótesis aún pendientes de prueba.',
'Como influenciam as instituições quem consegue transformar o desejo de filhos em vida familiar? Este ensaio científico e filosófico examina a fertilidade, a personalidade e os ambientes sociais. Distingue seleção genética, mudança cultural, filtragem social e transformações demográficas. Os capítulos comparam vida urbana, redes de parentesco e dificuldades de medir a personalidade entre culturas. Quatro cenários futuros exploram tensões entre pertença, autonomia e mediação algorítmica. Um mapa das evidências separa resultados estabelecidos de hipóteses ainda por testar.',
'Come influiscono le istituzioni sulla possibilità di trasformare il desiderio di figli in vita familiare? Questo saggio scientifico e filosofico esamina fertilità, personalità e ambienti sociali. Distingue selezione genetica, cambiamento culturale, filtraggio sociale e trasformazioni demografiche. I capitoli confrontano vita urbana, reti di parentela e difficoltà nella misurazione interculturale della personalità. Quattro scenari futuri esplorano tensioni tra appartenenza, autonomia e mediazione algoritmica. Una mappa delle prove distingue risultati consolidati da ipotesi ancora da verificare.',
'Cum influențează instituțiile cine poate transforma dorința de copii într-o viață de familie? Acest eseu științific și filosofic examinează fertilitatea, personalitatea și mediile sociale. El distinge selecția genetică, schimbarea culturală, filtrarea socială și transformările demografice. Capitolele compară viața urbană, rețelele de rudenie și dificultățile măsurării personalității între culturi. Patru scenarii de viitor explorează tensiunile dintre apartenență, autonomie și medierea algoritmică. O hartă a dovezilor separă rezultatele stabilite de ipotezele care încă trebuie testate.',
'Jak instytucje wpływają na to, kto może przełożyć pragnienie posiadania dzieci na życie rodzinne? Ten esej naukowy i filozoficzny bada dzietność, osobowość i środowiska społeczne. Rozróżnia selekcję genetyczną, zmianę kulturową, filtrowanie społeczne i przemiany demograficzne. Rozdziały porównują życie miejskie, sieci pokrewieństwa i trudności międzykulturowego pomiaru osobowości. Cztery scenariusze przyszłości badają napięcia między przynależnością, autonomią i pośrednictwem algorytmicznym. Mapa dowodów oddziela ustalone wyniki od hipotez wymagających dalszych testów.'
]
kws=[
'fertility|personality|cultural evolution|genetic selection|urbanization|kinship networks|heritability|demographic change|social institutions|reproductive autonomy',
'fécondité|personnalité|évolution culturelle|sélection génétique|urbanisation|réseaux de parenté|héritabilité|changement démographique|institutions sociales|autonomie reproductive',
'Fertilität|Persönlichkeit|kulturelle Evolution|genetische Selektion|Urbanisierung|Verwandtschaftsnetze|Heritabilität|demografischer Wandel|soziale Institutionen|reproduktive Autonomie',
'fertilidad|personalidad|evolución cultural|selección genética|urbanización|redes de parentesco|heredabilidad|cambio demográfico|instituciones sociales|autonomía reproductiva',
'fertilidade|personalidade|evolução cultural|seleção genética|urbanização|redes de parentesco|herdabilidade|mudança demográfica|instituições sociais|autonomia reprodutiva',
'fertilità|personalità|evoluzione culturale|selezione genetica|urbanizzazione|reti di parentela|ereditabilità|cambiamento demografico|istituzioni sociali|autonomia riproduttiva',
'fertilitate|personalitate|evoluție culturală|selecție genetică|urbanizare|rețele de rudenie|heritabilitate|schimbare demografică|instituții sociale|autonomie reproductivă',
'dzietność|osobowość|ewolucja kulturowa|selekcja genetyczna|urbanizacja|sieci pokrewieństwa|odziedziczalność|zmiana demograficzna|instytucje społeczne|autonomia reprodukcyjna']
m={'schemaVersion':1,'id':r['bookId'],'sourceId':'Societatea_care_ne_selecteaza','sourceAliases':['Societatea_care_ne_selecteaza'],'route':['the','society','that','selects','us'],'category':'Society & Institutions','group':'science','title':dict(zip(codes,titles)),'subtitle':dict(zip(codes,subs)),'shortDescription':dict(zip(codes,desc)),'aboutBook':{c:[d] for c,d in zip(codes,desc)},'shortDescriptionEditorial':{'method':'active-LLM-authored','sourceSha256':r['sha256'],'sentencesPerLanguage':6,'status':'reviewed-intake'},'keywordIds':[keyword_identifier(k) for k in kws[0].split('|')],'keywords':{c:k.split('|') for c,k in zip(codes,kws)},'coverUrl':{c:f'{c}/cover.webp' for c in codes},'editions':{c:{'book':f'{c}/book.html','cover':f'{c}/cover.webp','sourceCover':f'{c}/cover.png','thumbnail':f'{c}/thumbnail.webp'} for c in codes},'availableLanguages':[]}
(w/'book/manifest.json').write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')
r['coverSource'].update(origin='generated-original-art',extractedFromDelivery=False,authorization='User explicitly requested an original representative cover for the text-only DOCX.',generator='Built-in image_gen',sourceContainsImages=False,visualReview='Title and subtitle correct; portrait city/courtyard illustration inspected at full output size.',promptFile='cover-prompt.txt')
r['changes']={'en':'First edition with complete English and Romanian readers, an evidence appendix and eight preserved tables.','ro':'Prima ediție cu lecturi integrale în engleză și română, anexă a dovezilor și opt tabele păstrate.'}
(w/'release.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
