from pathlib import Path
import json
w=Path(__file__).parent/'summary-en';syn=json.loads((w/'synthesis.json').read_text());sections=[]
def para(t,ids,clusters):return {'text':t,'sourceUnitIds':[f'u{x:06}' for x in ids],'clusterIds':[f'cluster-{x:03}' for x in clusters],'audit':{'meaningPreserved':True,'factsPreserved':True,'noUnsupportedClaim':True}}
data=[[
("A society may celebrate education, independence, and professional mobility while making family life difficult for people pursuing those values. The Society That Selects Us begins from this contradiction. Its question is not whether populations can be ranked by biological worth, but how institutions distribute the possibility of having a future. Housing, employment, care, partnership, and prestige can influence whose intentions become descendants. These effects need not be deliberate, and their most immediate consequences may concern culture and demography rather than genes.",[5,14,18,58],[1]),
("The argument depends on separating four mechanisms. Genetic selection connects heritable variation with reproductive success. Cultural selection changes the prevalence of ideas and norms. Social filtering attracts or excludes people with particular profiles, while demographic selection changes subgroup proportions when fertility differs. A city that attracts adventurous migrants has not necessarily produced adventurous genes. A religious community can grow through transmitted family norms without demonstrating any genetic advantage. Confusing these processes makes dramatic stories easier and causal explanation weaker.",[6,62],[1]),
("Lower mortality does not abolish natural selection: mating, reproductive timing, and number of descendants can still vary. Yet heritability and fertility differences alone cannot establish a genetic destiny. The book also separates local demographic decline from species extinction. Global projections differ, populations have different age structures, and migration changes local trajectories. More subtle losses can occur long before a population vanishes: a language stops passing between generations, a profession loses apprentices, or an institution survives only by continually recruiting outsiders. The relevant question becomes which social arrangements can continue without coercion.",[53,54,65,70,71,73,75,77,363],[1,2])],
[
("Two people can want the same number of children while facing different probabilities of achieving that wish. One has affordable housing, predictable work, and relatives nearby; the other faces expensive rent, long commutes, and repeated relocation. The book identifies five filters connecting preference to family formation: partner markets, timing, opportunity cost, care infrastructure, and prestige. These are intervening mechanisms, not background scenery. The same personality can have different reproductive consequences when institutions alter the costs of acting on it.",[99,100,111],[3]),
("Universities, occupations, and dating platforms shape whom people meet and can encourage assortative mating between similar partners. Lengthy education may delay a first birth, while career rewards can demand greatest availability during the years when families form. Raising children also relies on cooperative care: grandparents, relatives, neighbors, and services supply support that two full-time workers cannot always replace alone. Prestige adds cultural transmission, because visible models of successful adulthood influence which lives people imitate and consider desirable.",[102,104,106,108,110],[3]),
("The marginal child makes these mechanisms concrete. The difference between one child and two or three may depend on a larger home, flexible working hours, or reliable after-school care. Housing and transport policy can therefore affect reproductive outcomes without intending any biological intervention. This is why the book resists treating lower urban fertility as an intrinsic property of cities. Urban living bundles costs, opportunities, mobility, and family norms. Its effects become intelligible when that package is unpacked, and when professional success is distinguished from the ability to sustain a family.",[87,93,94,106,111],[3])],
[
("Personality enters this account with strict methodological limits. Heritability describes how genetic differences relate to variation within a particular population and environment; it does not identify a predetermined fraction of an individual's character. Nor does high heritability within groups prove that differences between groups are genetic. The book uses height and nutrition to clarify the distinction: environmental change can shift a population's average even when genetic variation explains much of the variation among its members.",[122,123,131],[4]),
("Cross-cultural personality scores introduce another problem: measurement invariance. Comparing averages requires confidence that an instrument measures comparable constructs on comparable scales. National stereotypes can enjoy widespread agreement while corresponding poorly to measured personality. China and India therefore appear as complex cases, not unified psychological characters. The discussion of rice agriculture includes criticism of the attractive cooperation hypothesis; clan research concerns institutional persistence rather than genetic causation. India's internal diversity likewise makes local family systems, samples, and contexts indispensable to interpretation.",[136,139,163,166,167,169,178,179,187],[4]),
("Migration further complicates comparison. People who leave are not necessarily a random sample, and moving can subsequently change them. The differences between a global city and its surrounding countryside may reflect both self-selection and socialization. Small or isolated communities can also constrain observable behavior through reputation, overlapping obligations, and limited occupational niches, even without genetic differences. These distinctions prevent geography, national identity, or the historical age of a civilization from becoming substitutes for an actual explanatory mechanism.",[193,194,198,199,174],[4])],
[
("One of the book's distinctive arguments concerns the diversity of niches. The Big Five personality structure was not robustly reproduced in the Tsimane research discussed here; this does not mean the people studied have simpler minds. A subsistence community may require correlated packages of behavior because the same adult must work, care, negotiate, and cooperate within overlapping relationships. Complex economies can support more combinations: a withdrawn specialist need not perform every social role equally well.",[142,204,205,206],[5,4]),
("The niche diversity hypothesis connects these viable combinations with more differentiated statistical personality dimensions. The cited comparative findings support an association, not definitive proof of causation. Institutional complexity may therefore protect variation rather than simply impose conformity. But the book adds a second stage: professional viability does not ensure reproductive continuity. A society can provide an unusually rich range of adult lives while making only some of those lives compatible with children. Cultural pluralism today and demographic diversity tomorrow need not move together. Freedom then requires more than formal permission to choose; it requires workable combinations of livelihood, community, and family.",[143,207,209,210,211,213,216],[5,4])],
[
("Psychopathy, paranoia, and psychiatric diagnoses test the limits of evolutionary storytelling. Estimates of psychopathy prevalence differ substantially between instruments, and trait questionnaires are not interchangeable with clinical assessment. A calm surgeon or a risk-tolerant entrepreneur is not thereby a psychopath. The hypothesis that exploitation can benefit when most people cooperate is not enough to establish modern genetic selection; reproductive effects, heritability, and alternative explanations still require evidence. Institutions can nevertheless reward or restrain exploitative behavior through accountability, transparency, and reputational feedback.",[224,225,227,231,232,233],[6]),
("Paranoid thinking is discussed as a continuum, with a proposed problem of threat calibration rather than proof that urbanization selects paranoia. Rational distrust of opaque institutions must remain distinguishable from clinical persecutory beliefs. The city itself has two sides: some studies associate urban living with higher mental-health risks, while density also supplies hospitals, universities, minority communities, and specialized relationships. Neither a uniformly healthy village nor a uniformly pathological metropolis fits this account. Urbanicity bundles exposures, resources, and residential selection.",[237,241,242,244,250,253,254],[6]),
("The persistence of heritable psychiatric vulnerability does not prove that a disorder is adaptive. Polygenic architecture, mixed effects, and mutation complicate such explanations; many severe diagnoses are associated with lower fertility in the evidence discussed. A score associated with a trait is also not equivalent to selection for a clinical diagnosis. The ethical response is consequently to reduce suffering, discrimination, and barriers to relationships, not to optimize society's genetic composition. Reproductive freedom includes people with disabilities and mental disorders.",[263,264,266,268,269,271,274],[6])],
[
("The book's four futures are thought experiments, not forecasts. The meritocratic megacity concentrates opportunity and specialization but may rely on new arrivals while making family continuity expensive. This does not establish an inevitable decline in intelligence: education, cognitive ability, and polygenic scores cannot simply be equated. The danger identified is an institutional contradiction between valued careers and reproductive possibilities. Communities whose support networks make family life feasible may persist under conditions that other strategies cannot sustain.",[281,283,284,286,287,289,290],[7]),
("The neo-tribal archipelago instead offers dense belonging, shared care, and strong norms. These may support cooperation and larger families, but they can narrow viable niches and make exit costly. Strong trust inside a group can coexist with hostility toward outsiders. The problem is therefore to retain community's benefits without giving communities total authority over members. The metropolis of proximity offers a different combination: dense cities with nearby services, suitable housing, stable neighborhoods, and permeable communities. It seeks to make family life compatible with professional diversity rather than force a return to a single social model.",[294,295,298,299,303,308,313,315,322],[7]),
("Algorithmic reproduction adds a quieter form of institutional influence. Ranking systems alter who becomes visible to potential partners, even when individuals make their own choices. Attention concentration does not automatically translate into reproductive outcomes; long-term evidence is needed. Genetic scoring creates further risks if uncertain probabilities become commercial hierarchies of human quality. AI may also reduce administrative burdens, coordinate care, or help isolated people find communities. The same technology can strengthen filters or remove arbitrary obstacles, depending on its objectives and design.",[329,330,332,333,335,336],[7]),
("The book favors a polycentric direction: many professional and cultural niches, practical support for family life, strong intermediate communities, and a genuine right to leave. This is a normative proposal, not an experimentally settled recipe. Its test is whether people can realize their own reproductive preferences with fewer unnecessary barriers. Birth rates alone cannot distinguish chosen childlessness from frustrated parenthood. Auditing institutions therefore means examining time, housing, care, partner access, and the gap between desired and realized fertility, rather than treating more births as the sole measure of success.",[318,319,322,348,350,352,356,358],[7,2])]]
for s,ps in zip(syn['outline'],data):sections.append({'id':s['id'],'heading':s['title'],'paragraphs':[para(*p) for p in ps]})
d={'title':'The Society That Selects Us','dek':'How institutions connect human differences, reproductive freedom, and the continuity of social life.','sections':sections,'conclusion':[para("A childless life can be complete and valuable; no argument about continuity makes reproduction an individual obligation. The book's final question concerns the environments we build together. Local institutions can each optimize their own rewards while collectively undermining the lives they need to continue. Making those filters visible allows pluralism to become a practical possibility across generations, not merely a declared ideal.",[364,366,360,368],[2])],'audit':{'sameLanguage':True,'centralMessagePreserved':True,'coherentEssay':True,'notes':'Unified thematic essay; all twenty chapters represented through mechanisms, comparative cautions, evidence boundaries and four conditional scenarios. No new advice or empirical claims added.'}}
(w/'draft.json').write_text(json.dumps(d,ensure_ascii=False,indent=2))
print('Approx words',sum(len(p['text'].split()) for s in sections for p in s['paragraphs'])+sum(len(p['text'].split()) for p in d['conclusion']))
