from pathlib import Path
import json
w=Path(__file__).parent/'summary-en';d=json.loads((w/'draft.json').read_text());s=json.loads((w/'synthesis.json').read_text());s['outline'][3]['clusterIds'].append('cluster-004')
ps=[('The causal distinction matters even when biological effects are measurable. An education-associated polygenic score can correlate with later reproduction, yet education is not a single inherited capacity and the score captures only part of variation. The surrounding institutions may explain much of the immediate pathway. Cultural norms can shift within a generation, while patterns observed in one population may not transfer elsewhere. A measured association is therefore a starting point for investigating mediation and context, rather than permission to announce the genetic direction of modern humanity.',[59,60,62,65],[1]),('The framework also changes how large institutions are judged. Villages rely on repeated encounters and personal reputation; states and bureaucracies make cooperation among strangers possible through documents, procedures, and audits. Those arrangements can preserve trust at scale, but weak feedback may also protect harmful conduct. Likewise, strong cultural norms may help a group coordinate under threats while imposing costs on nonconformity. The book treats these as contextual tradeoffs, asking which behaviors an institution rewards and whether those rewards actually connect to reproduction.',[150,151,152,154,155,157,158],[3]),('The evidence appendix makes this restraint part of the method. It separates established observations, suggestive associations, and speculative proposals, then asks what findings could weaken each claim. Better cross-cultural instruments could improve comparisons; longitudinal changes could test niche diversity; urban and family interventions could challenge the proposed benefits of proximity. This keeps the preferred future open to correction. Institutional design remains a reasoned hypothesis to examine, not a conclusion guaranteed by the existence of demographic change.',[371,383,391,423],[4])]
for idx,(text,ids,cs) in zip([0,1,2],ps):d['sections'][idx]['paragraphs'].append({'text':text,'sourceUnitIds':[f'u{x:06}' for x in ids],'clusterIds':[f'cluster-{x:03}' for x in cs],'audit':{'meaningPreserved':True,'factsPreserved':True,'noUnsupportedClaim':True}})
# Preserve exact evidence coverage in analyses and synthesis.
for c in s['clusters']:
 referenced={u for sec in d['sections'] for p in sec['paragraphs'] if c['id'] in p['clusterIds'] for u in p['sourceUnitIds']}
 for ap in (w/'analyses').glob('*.json'):
  a=json.loads(ap.read_text())
  if a['chapterId'] not in c['chapterIds']:continue
  b=json.loads((w/'batches'/ap.name).read_text());add=referenced & {u['id'] for u in b['units']};a['ideas'][0]['sourceUnitIds']=sorted(set(a['ideas'][0]['sourceUnitIds'])|add);ap.write_text(json.dumps(a,ensure_ascii=False,indent=2));c['sourceUnitIds']=sorted(set(c['sourceUnitIds'])|add)
(w/'synthesis.json').write_text(json.dumps(s,ensure_ascii=False,indent=2));(w/'draft.json').write_text(json.dumps(d,ensure_ascii=False,indent=2))
