from pathlib import Path
from lxml import html,etree
from weasyprint import HTML,CSS
import hashlib,json,shutil
w=Path(__file__).resolve().parent;pub=w/'publication/en';pub.mkdir(parents=True,exist_ok=True);src=w/'book/en/full_content.html';doc=html.fromstring(src.read_bytes());main=doc.xpath('//main')[0]
# Preserve every reader element and its inline emphasis. Only print layout differs.
cover=etree.Element('section',{'class':'cover','aria-label':'Book cover'});etree.SubElement(cover,'img',src='cover.png',alt='Who Will Inherit the World?');main.insert(0,cover)
shutil.copy2(w/'generated-cover-final.png',pub/'cover.png')
for style in doc.xpath('//style'):style.getparent().remove(style)
css='''@page{size:152.4mm 228.6mm;margin:17mm 17mm 18mm;@bottom-center{content:counter(page);font-family:"Noto Serif";font-size:8pt;color:#64706a}}@page cover{margin:0;@bottom-center{content:none}}html{color:#23322e;background:white}body{margin:0;font-family:"Noto Serif",serif;font-size:10pt;line-height:1.36}main{margin:0;padding:0}.cover{page:cover;width:152.4mm;height:228.6mm;break-after:page}.cover img{width:100%;height:100%;object-fit:cover}h1,h2,h3{font-family:"Red Hat Display",sans-serif;font-weight:700;line-height:1.2;color:#244c40;break-after:avoid;page-break-after:avoid}h1{font-size:22pt;margin:0 0 20pt;break-before:page;padding-top:12pt;letter-spacing:-.4pt}h1#p0000{font-size:34pt;padding-top:23mm;line-height:1.08;letter-spacing:-1pt}h2{font-size:14pt;margin:19pt 0 10pt}p{margin:0 0 7pt;orphans:3;widows:3;text-align:justify;hyphens:auto}h1+p,h2+p{break-before:avoid}.subtitle{font-size:16pt;font-style:italic;line-height:1.35;text-align:left;margin:15pt 0 18pt}#p0002{font-size:10pt;text-align:left;color:#61726a}#p0003{font-style:italic;margin-top:26pt;text-align:left}#p0004{text-align:left;margin-top:15pt;font-family:"Red Hat Display";font-size:9pt}#p0005{break-before:page;font-size:22pt;margin:0 0 16pt}ul,ol{padding-left:15pt;margin:8pt 0 12pt}li{margin-bottom:6pt;orphans:3;widows:3}strong{font-weight:700}em{font-style:italic}.callout{background:#edf2ec;padding:9pt 11pt;border-radius:3pt;break-inside:avoid;text-align:left;font-size:9.3pt;line-height:1.4;margin:12pt 0}.bibliography{font-size:8.4pt;line-height:1.38;text-align:left;overflow-wrap:anywhere;break-inside:avoid;margin-bottom:8pt}table{width:100%;border-collapse:collapse;margin:12pt 0;font-size:8pt;line-height:1.28;table-layout:fixed}td,th{vertical-align:top;text-align:left;padding:6pt;border-bottom:.4pt solid #b7c7bc}th{font-family:"Red Hat Display";color:#244c40;background:#edf2ec}table p{text-align:left;margin:0 0 4pt;orphans:1;widows:1}tr{break-inside:avoid}.source-toc{font-family:"Red Hat Display";font-size:7.6pt;line-height:1.25;margin:0}.source-toc td{width:50%;border:0;padding:0 8pt 0 0}.source-toc p{margin:0 0 5pt;break-inside:avoid}.source-toc tr{break-inside:auto}a{color:inherit;text-decoration:none}'''
style=etree.SubElement(doc.find('head'),'style');style.text=css
path=pub/'publication.html';path.write_bytes(etree.tostring(doc,method='html',encoding='utf-8',doctype='<!doctype html>'))
out=w/'book/en/book.pdf';HTML(filename=str(path)).write_pdf(str(out),pdf_tags=True)
(w/'pdf-build.json').write_text(json.dumps(dict(sourceHtmlSha256=hashlib.sha256(src.read_bytes()).hexdigest(),coverSha256=hashlib.sha256((pub/'cover.png').read_bytes()).hexdigest(),pdfSha256=hashlib.sha256(out.read_bytes()).hexdigest(),engine='WeasyPrint; locally installed isolated dependencies; no external resources',pageSize='6 x 9 inches',fonts=['Noto Serif','Red Hat Display'],sourceText='All reader elements preserved, cover prepended; no content edits'),indent=2)+'\n');print(out)
