from pathlib import Path
import json,sys,hashlib
sys.path.insert(0,'tools');from build_books import keyword_identifier
w=Path('.book-work/cinevamostenilumea-v1-d8c4cc390248');langs=['en','fr','de','es','pt','it','ro','pl'];rel=json.loads((w/'release.json').read_text())
titles=['Who Will Inherit the World?','Qui héritera du monde ?','Wer wird die Welt erben?','¿Quién heredará el mundo?','Quem herdará o mundo?','Chi erediterà il mondo?','Cine va moșteni lumea?','Kto odziedziczy świat?']
subs=['Flaws, Fertility, and the Unseen Selection of Civilizations','Défauts, fécondité et sélection invisible des civilisations','Schwächen, Fertilität und die unsichtbare Selektion der Zivilisationen','Defectos, fecundidad y la selección invisible de las civilizaciones','Defeitos, fecundidade e a seleção invisível das civilizações','Difetti, fecondità e la selezione invisibile delle civiltà','Defecte, fertilitate și selecția nevăzută a civilizațiilor','Wady, dzietność i niewidoczna selekcja cywilizacji']
texts={
'en':['This scientific and philosophical essay examines how social environments shape reproductive differences.','It connects fertility, personality, inherited variation, and cultural transmission.','Historical chapters explore marriage rules, migration, religion, cities, and institutions.','The discussion separates evidence from hypotheses about evolutionary change.','Seven future scenarios consider AI, community continuity, and reproductive autonomy.','Its central question concerns the tension between what persists and what deserves to persist.'],
'fr':['Cet essai scientifique et philosophique examine comment les milieux sociaux façonnent les différences de reproduction.','Il relie fécondité, personnalité, variation héréditaire et transmission culturelle.','Les chapitres historiques explorent les règles matrimoniales, les migrations, la religion, les villes et les institutions.','La discussion distingue les preuves des hypothèses sur le changement évolutif.','Sept scénarios futurs abordent l’IA, la continuité des communautés et l’autonomie reproductive.','La question centrale porte sur la tension entre ce qui persiste et ce qui mérite de persister.'],
'de':['Dieser wissenschaftliche und philosophische Essay untersucht, wie soziale Umwelten Unterschiede in der Fortpflanzung prägen.','Er verbindet Fertilität, Persönlichkeit, erbliche Variation und kulturelle Weitergabe.','Historische Kapitel behandeln Heiratsregeln, Migration, Religion, Städte und Institutionen.','Die Erörterung unterscheidet Belege von Hypothesen über evolutionären Wandel.','Sieben Zukunftsszenarien betrachten KI, den Fortbestand von Gemeinschaften und reproduktive Selbstbestimmung.','Im Mittelpunkt steht die Spannung zwischen dem, was fortbesteht, und dem, was fortbestehen sollte.'],
'es':['Este ensayo científico y filosófico examina cómo los entornos sociales moldean las diferencias reproductivas.','Relaciona fecundidad, personalidad, variación hereditaria y transmisión cultural.','Los capítulos históricos exploran reglas matrimoniales, migración, religión, ciudades e instituciones.','La discusión distingue las pruebas de las hipótesis sobre el cambio evolutivo.','Siete escenarios futuros consideran la IA, la continuidad comunitaria y la autonomía reproductiva.','Su pregunta central aborda la tensión entre lo que perdura y lo que merece perdurar.'],
'pt':['Este ensaio científico e filosófico examina como os ambientes sociais moldam as diferenças reprodutivas.','Relaciona fecundidade, personalidade, variação hereditária e transmissão cultural.','Os capítulos históricos exploram regras matrimoniais, migração, religião, cidades e instituições.','A discussão distingue evidências de hipóteses sobre a mudança evolutiva.','Sete cenários futuros abordam a IA, a continuidade das comunidades e a autonomia reprodutiva.','A pergunta central trata da tensão entre aquilo que persiste e aquilo que merece persistir.'],
'it':['Questo saggio scientifico e filosofico esamina come gli ambienti sociali plasmano le differenze riproduttive.','Collega fecondità, personalità, variazione ereditaria e trasmissione culturale.','I capitoli storici esplorano regole matrimoniali, migrazione, religione, città e istituzioni.','La discussione distingue le prove dalle ipotesi sul cambiamento evolutivo.','Sette scenari futuri considerano l’IA, la continuità delle comunità e l’autonomia riproduttiva.','La domanda centrale riguarda la tensione tra ciò che persiste e ciò che merita di persistere.'],
'ro':['Acest eseu științific și filosofic examinează cum mediile sociale modelează diferențele reproductive.','El conectează fertilitatea, personalitatea, variația ereditară și transmiterea culturală.','Capitolele istorice explorează regulile căsătoriei, migrația, religia, orașele și instituțiile.','Discuția separă dovezile de ipotezele despre schimbarea evolutivă.','Șapte scenarii de viitor analizează AI, continuitatea comunităților și autonomia reproductivă.','Întrebarea centrală privește tensiunea dintre ceea ce persistă și ceea ce merită să persiste.'],
'pl':['Ten esej naukowy i filozoficzny bada, jak środowiska społeczne kształtują różnice w rozrodczości.','Łączy dzietność, osobowość, zmienność dziedziczną i przekaz kulturowy.','Rozdziały historyczne omawiają reguły małżeńskie, migrację, religię, miasta i instytucje.','Dyskusja oddziela dowody od hipotez dotyczących zmian ewolucyjnych.','Siedem scenariuszy przyszłości rozważa AI, ciągłość wspólnot i autonomię reprodukcyjną.','Główne pytanie dotyczy napięcia między tym, co trwa, a tym, co zasługuje na przetrwanie.']}
terms={
'en':'fertility|demography|behavioral genetics|personality|cultural evolution|heritability|sexual selection|migration|kinship|endogamy|religion|urbanization|family policy|reproductive autonomy|artificial intelligence|evolutionary anthropology|population genetics|social institutions|epistemic pluralism|intergenerational change',
'fr':'fécondité|démographie|génétique comportementale|personnalité|évolution culturelle|héritabilité|sélection sexuelle|migration|parenté|endogamie|religion|urbanisation|politique familiale|autonomie reproductive|intelligence artificielle|anthropologie évolutionniste|génétique des populations|institutions sociales|pluralisme épistémique|changement intergénérationnel',
'de':'Fertilität|Demografie|Verhaltensgenetik|Persönlichkeit|kulturelle Evolution|Heritabilität|sexuelle Selektion|Migration|Verwandtschaft|Endogamie|Religion|Urbanisierung|Familienpolitik|reproduktive Selbstbestimmung|künstliche Intelligenz|evolutionäre Anthropologie|Populationsgenetik|soziale Institutionen|epistemischer Pluralismus|generationsübergreifender Wandel',
'es':'fecundidad|demografía|genética conductual|personalidad|evolución cultural|heredabilidad|selección sexual|migración|parentesco|endogamia|religión|urbanización|política familiar|autonomía reproductiva|inteligencia artificial|antropología evolutiva|genética de poblaciones|instituciones sociales|pluralismo epistémico|cambio intergeneracional',
'pt':'fecundidade|demografia|genética comportamental|personalidade|evolução cultural|herdabilidade|seleção sexual|migração|parentesco|endogamia|religião|urbanização|política familiar|autonomia reprodutiva|inteligência artificial|antropologia evolutiva|genética populacional|instituições sociais|pluralismo epistémico|mudança intergeracional',
'it':'fecondità|demografia|genetica comportamentale|personalità|evoluzione culturale|ereditabilità|selezione sessuale|migrazione|parentela|endogamia|religione|urbanizzazione|politica familiare|autonomia riproduttiva|intelligenza artificiale|antropologia evolutiva|genetica delle popolazioni|istituzioni sociali|pluralismo epistemico|cambiamento intergenerazionale',
'ro':'fertilitate|demografie|genetică comportamentală|personalitate|evoluție culturală|ereditabilitate|selecție sexuală|migrație|rudenie|endogamie|religie|urbanizare|politici familiale|autonomie reproductivă|inteligență artificială|antropologie evolutivă|genetica populațiilor|instituții sociale|pluralism epistemic|schimbare intergenerațională',
'pl':'dzietność|demografia|genetyka behawioralna|osobowość|ewolucja kulturowa|odziedziczalność|dobór płciowy|migracja|pokrewieństwo|endogamia|religia|urbanizacja|polityka rodzinna|autonomia reprodukcyjna|sztuczna inteligencja|antropologia ewolucyjna|genetyka populacyjna|instytucje społeczne|pluralizm epistemiczny|zmiana międzypokoleniowa'}
for c in langs:assert len(texts[c])==6 and all(len(t.split())<=22 for t in texts[c]);assert len(set(terms[c].split('|')))==20
p=dict(schemaVersion=1,id=rel['bookId'],sourceId='Cine_va_mosteni_lumea',sourceAliases=['Cine va mosteni lumea'],route=['who','will','inherit','the','world'],category='Society & Institutions',group='society',title=dict(zip(langs,titles)),subtitle=dict(zip(langs,subs)),shortDescription={c:' '.join(texts[c]) for c in langs},aboutBook={c:[' '.join(texts[c][:3]),' '.join(texts[c][3:])] for c in langs},shortDescriptionEditorial=dict(method='active-LLM-authored',sourceSha256=rel['sha256'],sentencesPerLanguage=6,status='reviewed-intake',scope='Source title, reading note, prologue, complete heading map and source-limit statement; full reader and final metadata review pending.'),keywordIds=[keyword_identifier(x) for x in terms['en'].split('|')],keywords={c:terms[c].split('|') for c in langs},coverUrl={c:f'{c}/cover.webp' for c in langs},thumbnailUrl={c:f'{c}/thumbnail.webp' for c in langs},editions={c:dict(book=f'{c}/book.html',cover=f'{c}/cover.webp',sourceCover=f'{c}/cover.png',thumbnail=f'{c}/thumbnail.webp') for c in langs},availableLanguages=[])
p['coverEditorial']=dict(sha256=json.loads((w/'cover-review.json').read_text())['sha256'],deliverySha256=rel['sha256'],origin='generated-original-art',extractedFromDelivery=False,authorization='User requested an original representative cover for the text-only DOCX.',generator='Built-in image_gen',sourceContainsImages=False,visualReview='Root approved final cover; correct English title/subtitle and plural intergenerational paths without deterministic hierarchy.')
(w/'book/manifest.json').write_text(json.dumps(p,indent=2,ensure_ascii=False)+'\n');rel['changes']={'en':'First English and Romanian reader editions of a scientific and philosophical essay on fertility, institutions, and cultural evolution.','ro':'Primele ediții de lectură în engleză și română ale unui eseu științific și filosofic despre fertilitate, instituții și evoluție culturală.'};(w/'release.json').write_text(json.dumps(rel,indent=2,ensure_ascii=False)+'\n')
print('Authored eight-language intake metadata with six short sentences and 20 real discovery terms per language.')
