from pathlib import Path
import json
w=Path(__file__).parent/'summary-job';syn=json.loads((w/'synthesis.json').read_text());sections=[]
def sec(n,paras):
 o=syn['outline'][n-1];sections.append(dict(id=o['id'],heading=o['title'],paragraphs=[dict(text=t,clusterIds=[f'cluster-{c:03d}' for c in cs],sourceUnitIds=[f'u{u:06d}' for u in us],audit=dict(meaningPreserved=True,factsPreserved=True,noUnsupportedClaim=True)) for t,cs,us in paras]))
sec(1,[
('Who Will Inherit the World? asks whether societies do more than educate their members: whether they also influence which ways of life continue. Its most unsettling example is ordinary rather than spectacular. Someone delays children until housing, work, finances and parenting conditions seem adequate. Another person belongs to a community that shares housing and care, making family formation easier. Neither needs to think about evolution. Their institutions have already changed the practical cost of becoming parents.',[1],[69,90,172,174,297,298]),
('The argument is not that prudent people inevitably disappear. It is that reproductive outcomes emerge within arrangements of prices, prestige, time, relationships and support. A city may attract educated workers while making family housing unaffordable. Professional certification may reward conscientiousness while consuming the years when its practitioners hoped to form families. Migration can keep such institutions lively without showing that their existing members reproduce themselves. Formal freedom and practical opportunity are therefore different questions.',[1],[265,266,267,314,315,316,317,318]),
('Continuation also means more than counting births. Evolutionary fitness concerns descendants who survive and reproduce; cultural persistence depends on whether children retain a community’s practices, whether outsiders join, and whether members leave. A group with more births need not transmit its culture more effectively. Small differences can accumulate, but the book’s arithmetic deliberately simplifies a world in which migration, mixed marriages, changing norms and fertility convergence interrupt any straight extrapolation.',[2],[96,104,105,107,109,251,253,306,307,308]),
('This distinction establishes the book’s central order of explanation: institutions and cultural strategies can change their representation quickly, while genetic changes in complex traits generally require more steps and more time. Selection describes what continues under particular conditions. It neither rewards moral merit nor tells a society which people deserve to exist.',[3,9],[77,101,102,106,459,460])])
sec(2,[
('A provocative account of demography can easily become a story in which intelligence declines and ruthlessness triumphs. The book repeatedly turns its own premise against that temptation. Findings about education, cognitive ability and fertility differ across countries, sexes and cohorts. Swedish and Norwegian male-register studies complicate the familiar claim that higher ability necessarily means fewer children. Education can postpone family formation, while ability, income, security or supportive policies can operate differently. These variables cannot be compressed into one universal law.',[4,5],[98,99,290,291,292,293]),
('Psychopathic traits provide another test. Some studies report positive fertility associations; others find negative or absent associations. Initial attractiveness, manipulation, impulsivity, long-term cooperation and parental investment can pull in opposing directions. An exploitative strategy may benefit when surrounded by trusting partners, then lose its advantage as exploitation becomes common. A label conceals the components that a particular environment actually rewards or penalizes.',[4],[136,145,146,147,148,149,150,151]),
('Nor should a clinical disorder be redescribed as a successful reproductive strategy. The book presents evidence of reduced fertility across several severe psychiatric diagnoses and distinguishes those diagnoses from moderate traits or genetic correlations. A variant can affect several outcomes, so an association between disease risk and fertility does not establish that illness causes reproductive success. Vulnerabilities may persist for multiple reasons; suffering does not need an imagined evolutionary gift to explain its existence.',[4,5],[116,117,161,162,163,164,165,166,167]),
('Heritability supplies no shortcut around these distinctions. It describes variation within a population and environment, not the genetic fraction of an individual or an unchangeable destiny. A questionnaire must measure comparable things before its scores can be compared across cultures. Likewise, empathy may support stable relationships and shared care as well as encourage caution. The suggestion that responsibility becomes reproductively costly remains a question about institutions, not an established law against empathy.',[4,5],[124,125,126,127,170,171,172,174,175])])
sec(3,[
('The historical comparisons replace portraits of national temperament with mechanisms that leave different kinds of evidence. In China, the rice–wheat comparison examines how demands for agricultural coordination can shape relational thinking and loyalties. The natural experiment discussed in the book suggests measurable differences within a generation. Its force lies partly in undermining a premature genetic explanation: social organization can change behavior without waiting for a new population genome.',[3,5],[221,222,223,224,227]),
('South Asian endogamy illustrates another timescale. Long-standing marriage boundaries can produce founder effects and marked genetic structure. A rule about whom people marry can therefore have biological consequences without anybody explicitly choosing genes. This establishes neither group superiority nor a caste personality. The contrast matters: learned cooperation and inherited population structure are both influenced by institutions, but they are not the same process.',[3,5],[229,230,231,232]),
('Even dramatic genetic traces may permit several social explanations. The post-Neolithic paternal-lineage bottleneck has been modeled through violent competition between clans, but another model produces a comparable pattern through patrilineal organization and unequal reproductive success without requiring violence. At Chichén Itzá, evidence of highly specific ritual violence coexists with long-term regional genetic continuity. Violence, cultural dominance and population replacement cannot simply stand in for one another.',[3,5],[195,196,197,198,199,239,240,241,242,243]),
('The same caution applies to cooperation. A group can restrain impulsive aggression internally while organizing cold violence against outsiders. Coordination is not automatically universal benevolence. Religious communities, meanwhile, can sustain high fertility through structured family institutions without being violently extremist. Retention, exit, schooling and shared care help explain their continuity. These cases ask what institutions do, rather than assigning an ancient civilization a personality score that no surviving evidence can supply.',[2,3,5,10],[187,188,189,191,192,246,248,249,250,251,253,427])])
sec(4,[
('Digital systems could reorganize these mechanisms. A matching platform that keeps people searching has a different objective from one that helps them form enduring relationships. Filters based on education, religion or politics can concentrate similar partners even across great distances. Physical cosmopolitanism can coexist with narrow social selection: people may share a city while living within increasingly separate networks of relationships and belief.',[1,6],[139,140,141,142,233,234,236,260,261,277]),
('AI may also alter the cost of family life in opposite directions. In one scenario, assistants handle administration, scheduling, tutoring and coordination, reducing burdens on people who already want children. In another, artificial companionship and personalized entertainment make a life without close human commitments more satisfying. Both effects could coexist across different groups. The book treats these as conditional possibilities to investigate, not measured demographic outcomes or predictions that technology must fulfill.',[6],[319,328,329,340,341,342,343,611]),
('Tutoring raises a further question: who transmits culture? Shared AI curricula could weaken a community’s parent-to-child transmission, while community-specific models could intensify it. The assistant becomes comparable to a school or other cultural institution because it selects explanations, conversational habits and permissible questions. Alignment still addresses real problems of control and safety, but knowledge mediation adds choices about evidence, uncertainty and whose arguments remain easy to articulate.',[6],[323,324,325,332,333,334,335]),
('The proposed response is neither an assistant that treats every claim as equally credible nor one that removes all unusual hypotheses. Exploration and endorsement must remain distinct. People should be able to formulate uncertain arguments while testing them rigorously and revising their beliefs. A system that substitutes its judgment for every user decision may reduce some immediate risks while weakening the capacity to reason through disagreement. Pluralism needs procedures for correction, not immunity from evidence.',[6,7],[336,337,338,348,349,350,351,352,353,354,355])])
sec(5,[
('Seven possible futures develop the stakes without naming a destined winner. The glass megalopolis combines abundance of options with delayed commitment. A neo-tribal archipelago makes belonging more important than geography. Pronatalist enclaves gain demographic weight through shared institutions and retention. A state that makes family life easier reduces unwanted barriers without choosing favored parents. These arrangements differ less in the personalities they celebrate than in which lives they make sustainable.',[2,6,8],[358,359,360,361,364,365,366,367,370,371,372,373,376,377,378,379]),
('The remaining scenarios expose harder trade-offs. A threatened fortress rewards discipline and cohesion, but crisis institutions may perpetuate the danger that justifies them. A partly post-biological society expands reproductive technology while confronting uncertain genetic predictions and unequal access. Finally, a reflective culture might voluntarily reject reproduction. Evolution cannot prove that ethical choice wrong, although a movement seeking a more caring future must consider how its values will reach that future.',[4,9,10],[381,382,383,384,385,387,388,389,390,391,393,394,395,396,397,398]),
('To keep scenarios from becoming mythology, the book proposes a three-generation test. First, establish that a trait is associated with relevant reproductive outcomes, rather than intentions or status alone. Next, identify what is transmitted and distinguish genetic inheritance from shared environment or cultural retention. Finally, ask whether descendants retain the reproductive association when their environment changes. An isolated survey is a clue; persistent relationships across generations offer a stronger basis for inference.',[5],[450,451,452,453,454,455,456]),
('The research agenda follows that logic. It calls for comparable psychological measures, completed fertility, migration histories, cultural retention and the actual cost of children across social circumstances. AI’s effects should be tested through observed relationship and family outcomes. Effect sizes matter alongside statistical significance. If an apparent reproductive penalty disappears where family infrastructure improves, the institution becomes a more persuasive explanation than an intrinsic defect in the trait.',[5],[490,491,492,493,494,495,496,497,498,499,553,555,556,558,559,560])])
sec(6,[
('The practical proposal is a reproductive neutrality of virtue: education, care, prudence and research should not become incompatible with family life through avoidable structural penalties. This does not mean rewarding supposedly superior parents. It means making wanted children more feasible through housing, flexible education, routes back into careers and shared care. Reducing the gap between desired and realized fertility makes choice more real without prescribing its outcome.',[8],[301,302,467,468,478,479,480,481,487]),
('Community support also needs freedom to leave. Belonging maintained through value and affection differs morally from retention enforced by fear or information isolation. Cooperation needs protection against exploitation, but defensive power requires limits and criticism. Diversity can preserve resilience without romanticizing untreated illness. These qualifications concern the kind of continuity worth sustaining, rather than an excuse to avoid designing institutions at all.',[8,10],[308,309,470,471,472,473,474,475,482,483,484,485]),
('A final ethical conflict remains. Preserving a valued culture does not justify creating people merely as its instruments, and reducing suffering does not automatically answer every question about future generations. Population ethics cannot be replaced by a fertility calculation. The book’s refusal of eugenics follows from this distinction: institutions can be examined and changed without assigning a moral rank to human beings or pretending that reproduction proves their worth.',[8,9],[459,460,461,462,464,465,466,478,487])])
con=[dict(text='The question is ultimately not which single human type will inherit the world. It is which social arrangements can continue without sacrificing the values that make continuation desirable. Selection becomes feedback to notice, not a sentence to obey. Freedom, care and thoughtful disagreement need sustainable forms of life; survival alone cannot tell us whether those forms deserve to endure.',clusterIds=['cluster-008','cluster-009'],sourceUnitIds=['u000516','u000517','u000518','u000519','u000520','u000521','u000522','u000523'],audit=dict(meaningPreserved=True,factsPreserved=True,noUnsupportedClaim=True))]
d=dict(title='Who Will Inherit the World?',dek='How institutions shape continuation, and why survival cannot decide what deserves to survive.',sections=sections,conclusion=con,audit=dict(sameLanguage=True,centralMessagePreserved=True,coherentEssay=True,notes='Thematic synthesis of all content parts, including source-bound objections, test criteria and moral tension. No external empirical validation claimed; selected examples summarize the book’s treatment.'))
(w/'draft.json').write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
