from pathlib import Path
import json
rows=[
('philosophy','Arhitectura realului','From Space and Time to Causality, Consciousness, and Existence','De la spațiu și timp la cauzalitate, conștiință și existență',[
'This essay explores space, time, causality, consciousness, and the meaning of existence.','It brings scientific explanations into conversation with philosophical questions.','Chapters examine natural laws, emergence, emotion, and the limits of understanding.','Thought experiments explore simulated worlds and unfamiliar forms of experience.','The text distinguishes empirical evidence from conjecture and imaginary experiments.','It asks how descriptions of reality shape intellectual and moral responsibility.']),
('philosophy','Arta de a ști ce contează','Wisdom, Education, and Artificial Intelligence','Înțelepciune, educație și inteligență artificială',[
'This book examines wisdom as a problem of judgment, education, and artificial intelligence.','It distinguishes possessing information from understanding situations and deciding what matters.','Classroom examples connect philosophical reflection with learning and the transfer of experience.','The PHRONESIS research programme investigates the distillation of contextual judgment.','Technical chapters discuss representations, evaluation, bias, and experiments that could challenge its hypotheses.','The central tension concerns what compression preserves when a decision depends on context.']),
('society','Cartea nu dă notificări','On Reading, Pocket Infinity, and the Right to Finish a Thought','Despre citit, infinitul din buzunar și dreptul de a gândi până la capăt',[
'This essay investigates reading among screens, podcasts, films, and conversational AI.','It considers books as artistic experiences, learning tools, and cultural institutions.','Chapters compare novels, textbooks, scientific articles, wikis, and short online formats.','The discussion examines attention, comprehension, listening, and the appeal of summaries.','It also questions the authority and moral prestige often granted to books.','The guiding question concerns the freedom to follow a thought to its end.']),
('science','Din reguli, lumi','Existence, Prediction, and Equivalence Under Finite Resources','Existență, predicție și echivalență sub resurse finite',[
'This research programme investigates how rules, states, and observers define descriptions of worlds.','It connects philosophical questions about existence with operational questions about prediction.','Chapters examine complexity, useful memory, causal intervention, and computational limits.','Model comparisons depend on explicit observations, resource budgets, and criteria of equivalence.','The text develops hypotheses, examples, and directions for empirical investigation.','Its central problem concerns what finite evidence can establish about apparently similar systems.']),
('philosophy','Frumosul: anatomia unei fascinații','From Bodies and Ideas to Art and Power','De la corp și idee la artă și putere',[
'This expanded essay explores beauty across bodies, ideas, art, nature, and social life.','It brings philosophical aesthetics into dialogue with perception, culture, and evolutionary research.','Chapters consider attraction, mathematical elegance, music, movement, and everyday surroundings.','Other discussions examine authenticity, fragility, status, and the aesthetics of power.','Examples ask why different forms can provoke equally compelling experiences of beauty.','The book investigates what admiration reveals and what fascination can conceal.']),
('society','Încă o încercare','Chance, Control, and the Illusion of Progress in the Age of AI','Hazard, control și iluzia progresului în epoca inteligenței artificiale',[
'This essay follows repeated attempts from games of chance to conversations with AI.','It examines uncertainty, perceived control, near misses, and the promise of another try.','Examples connect poker and strategy games with discovery and programming agents.','The discussion distinguishes encouragement, persuasive explanations, and independently verifiable progress.','Chapters also consider emotional involvement, confirmation, and the limits of clinical evidence.','Its recurring question concerns what remains after enthusiasm and repeated attempts.']),
('philosophy','Între credință și dovadă','Science, Religion, and the Temptation of Certainty','Știința, religia și tentația certitudinii',[
'This agnostic investigation examines science, religion, and competing claims to certainty.','Twenty-five historical dossiers explore beliefs associated with influential thinkers.','The discussion separates biographical testimony from scientific and philosophical arguments.','Chapters clarify materialism, atheism, agnosticism, and the boundaries of expert authority.','Educational questions connect intellectual history with evidence and responsibility.','The book asks how uncertainty can coexist with meaningful differences between claims.']),
('society','Libertatea și prețul ei','Choice, Responsibility, and the Costs Borne by Others','Alegere, răspundere și costurile suportate de ceilalți',[
'This essay investigates freedom through choice, responsibility, and unequal power.','It asks who can act and who bears the consequences of other people’s decisions.','Philosophical arguments meet scientific questions and ordinary social situations.','The discussion considers the relationship between personal autonomy and collective obligations.','Institutions and unequal opportunities complicate apparently simple accounts of individual choice.','The central tension concerns the conditions and costs of living freely together.']),
('philosophy','Lumea nu citește ecuații','Natural Laws, Emergence, and the Limits of Understanding','Legile naturii, emergența și limitele înțelegerii',[
'This essay asks what natural laws are and how explanations acquire their authority.','It connects scientific models with philosophical questions about order and reality.','Chapters explore emergence, the origin of regularities, and the limits of understanding.','The possibility of a simulated world becomes a test of competing descriptions.','Thought experiments distinguish observed patterns from claims about underlying mechanisms.','Its guiding question concerns the relationship between the world and the equations describing it.']),
('technology','Mașini de înțelegere prin circuite','SOP Lang, Sufficient Representations, and Controlled Reasoning','SOP Lang, reprezentări suficiente și construcția controlată a raționamentului',[
'This course develops a research programme for reasoning through circuits and sufficient representations.','It introduces SOP Lang alongside mathematical tools for describing partial information.','Chapters examine relations, information orders, abstract interpretation, and fixed points.','Examples investigate correlations that individual circuit connections may fail to preserve.','The discussion separates executing, verifying, and discovering a useful construction.','Its central question asks what representations must retain so reasoning can continue.']),
('technology','Meta-Rational Pragmatics','Understanding as Learning Executable Distinctions','Înțelegerea ca învățare a distincțiilor executabile',[
'This research course examines understanding as the learning of executable distinctions.','It connects representation, interpretation, uncertainty, and action within an operational architecture.','Mathematical chapters introduce equivalence, sufficient states, predictive models, and abstract interpretation.','Examples study counterexamples, refinement, information loss, and the diagnosis of errors.','The programme includes applications and proposed experiments for testing its claims.','Its central question concerns which distinctions an agent must preserve to act competently.']),
('technology','Noutatea care seamănă cu trecutul','Can Language Models Recognize What They Have Never Encountered?','Pot modelele lingvistice să recunoască ceea ce nu au mai întâlnit?',[
'This research monograph investigates how language models evaluate unfamiliar contributions.','It distinguishes novelty from rarity, truth, value, and perceived originality.','Chapters examine familiarity bias, semantic smoothing, and information lost through representation.','Formal examples connect sufficient representations with limits on evaluating new ideas.','Experimental proposals include finite circuits, historical research cases, and evidence registers.','The central tension concerns an evaluator trained on the past judging departures from it.']),
('society','Responsabilitatea','What We Owe a World We Did Not Choose','Cât datorăm unei lumi pe care nu am ales-o',[
'This essay examines responsibility from childhood and ordinary decisions to institutions and divine creation.','It distinguishes causing harm, answering for actions, and responding to suffering.','Examples consider poverty, work, citizenship, scientific knowledge, and automated decisions.','Philosophical arguments meet research on agency, cooperation, and collective behavior.','The discussion explores obligations toward people who cannot answer for themselves.','Its central question concerns what a finite person owes an unchosen world.']),
('society','Dreptul de a copia','Copyright, Trademarks, and Creative Work in the Age of AI','Drepturi de autor, mărci și creație în epoca inteligenței artificiale',[
'This course explores copyright, trademarks, and creative work in the age of AI.','It compares international foundations with legal differences across several jurisdictions.','Book rewriting and software reimplementation provide recurring practical cases.','Chapters distinguish expression, function, reputation, licensing, and the public domain.','The discussion also examines provenance, enforcement, and the limits of technical protection.','Its central question asks what creators can protect when equivalent results can be produced differently.']),
('business','Rețeaua intențiilor','How Personal AI Agents Could Rebuild Discovery, Trust, and Work','Cum ar putea agenții AI personali să transforme descoperirea, încrederea și munca',[
'This investment thesis explores a network of agents representing personal and organizational intentions.','It examines discovery problems in hiring, investment, research collaboration, and local services.','Chapters investigate reciprocal qualification, evidence exchange, negotiation, and contextual reputation.','The proposed infrastructure raises questions about privacy, fraud, decentralization, and human approval.','Product and market discussions consider early adoption, operational demands, and network economics.','Its central tension concerns effective representation without surrendering judgment or control.']),
('fiction','Ultimul naiv','Kindness, Power, and the Price of Good Faith','Bunătate, putere și prețul bunei-credințe',[
'This philosophical monologue follows a fictional narrator questioning the price of good faith.','Memories and imagined encounters connect kindness with family, school, work, and belief.','The narrator examines whether trusted virtues can also make someone easier to exploit.','Arguments about cooperation and competition complicate this growing suspicion.','Literary scenes and thought experiments explore responsibility, power, and the need for counterevidence.','The book asks what distrust might cost a person who still wants to remain kind.'])]
books=json.loads(Path('.book-work/intake-20260911/books.json').read_text())
for b,(group,ro,sub,subro,sentences) in zip(books,rows):
 assert len(sentences)==6 and all(len(s.split())<=22 for s in sentences)
 b.update(group=group,romanianTitle=ro,subtitle=sub,romanianSubtitle=subro,sentences=sentences)
Path('.book-work/intake-20260911/editorial.json').write_text(json.dumps(books,ensure_ascii=False,indent=2)+'\n')
