from pathlib import Path
import json
books=json.loads(Path('.book-work/intake-20260911/books.json').read_text())
titlefix={2:{'fr':'Le livre n’envoie pas de notifications','pl':'Książka nie wysyła powiadomień'},3:{'de':'Aus Regeln werden Welten','es':'De las reglas, mundos','it':'Dalle regole, mondi','pl':'Z reguł powstają światy'},5:{'fr':'Encore une tentative','de':'Noch ein Versuch','es':'Un intento más','it':'Un altro tentativo','pl':'Jeszcze jedna próba'},7:{'it':'La libertà e il suo prezzo'},8:{'pl':'Świat nie czyta równań'},10:{'fr':'Pragmatique métarationnelle','es':'Pragmática metarracional','pl':'Pragmatyka metaracjonalna'},11:{'it':'La novità che somiglia al passato','pl':'Nowość przypominająca przeszłość'},14:{'de':'Das Netzwerk der Intentionen'},15:{'fr':'Le dernier naïf','de':'Der letzte Naive','es':'El último ingenuo','pt':'O último ingénuo','it':'L’ultimo ingenuo','pl':'Ostatni naiwny'}}
subs='''De l’espace et du temps à la causalité, la conscience et l’existence|Von Raum und Zeit zu Kausalität, Bewusstsein und Existenz|Del espacio y el tiempo a la causalidad, la conciencia y la existencia|Do espaço e do tempo à causalidade, consciência e existência|Dallo spazio e dal tempo alla causalità, alla coscienza e all’esistenza|Od przestrzeni i czasu do przyczynowości, świadomości i istnienia
Sagesse, éducation et intelligence artificielle|Weisheit, Bildung und künstliche Intelligenz|Sabiduría, educación e inteligencia artificial|Sabedoria, educação e inteligência artificial|Saggezza, educazione e intelligenza artificiale|Mądrość, edukacja i sztuczna inteligencja
Lire, l’infini dans la poche et le droit d’aller au bout d’une pensée|Lesen, Unendlichkeit in der Tasche und das Recht, einen Gedanken zu Ende zu denken|Lectura, infinito de bolsillo y derecho a pensar hasta el final|Leitura, infinito no bolso e direito de pensar até ao fim|Lettura, infinito in tasca e diritto di pensare fino in fondo|Czytanie, nieskończoność w kieszeni i prawo do doprowadzenia myśli do końca
Existence, prédiction et équivalence avec des ressources finies|Existenz, Vorhersage und Äquivalenz bei endlichen Ressourcen|Existencia, predicción y equivalencia con recursos finitos|Existência, previsão e equivalência com recursos finitos|Esistenza, previsione ed equivalenza con risorse finite|Istnienie, przewidywanie i równoważność przy skończonych zasobach
Des corps et des idées à l’art et au pouvoir|Von Körpern und Ideen zu Kunst und Macht|De los cuerpos y las ideas al arte y al poder|Dos corpos e das ideias à arte e ao poder|Dai corpi e dalle idee all’arte e al potere|Od ciał i idei do sztuki i władzy
Hasard, contrôle et illusion du progrès à l’ère de l’IA|Zufall, Kontrolle und die Illusion des Fortschritts im Zeitalter der KI|Azar, control e ilusión del progreso en la era de la IA|Acaso, controlo e ilusão do progresso na era da IA|Caso, controllo e illusione del progresso nell’epoca dell’IA|Przypadek, kontrola i złudzenie postępu w epoce AI
Science, religion et tentation de la certitude|Wissenschaft, Religion und die Versuchung der Gewissheit|Ciencia, religión y tentación de la certeza|Ciência, religião e tentação da certeza|Scienza, religione e tentazione della certezza|Nauka, religia i pokusa pewności
Choix, responsabilité et coûts supportés par les autres|Wahl, Verantwortung und die von anderen getragenen Kosten|Elección, responsabilidad y costes soportados por otros|Escolha, responsabilidade e custos suportados pelos outros|Scelta, responsabilità e costi sostenuti dagli altri|Wybór, odpowiedzialność i koszty ponoszone przez innych
Lois naturelles, émergence et limites de la compréhension|Naturgesetze, Emergenz und die Grenzen des Verstehens|Leyes naturales, emergencia y límites de la comprensión|Leis naturais, emergência e limites da compreensão|Leggi naturali, emergenza e limiti della comprensione|Prawa natury, emergencja i granice rozumienia
SOP Lang, représentations suffisantes et raisonnement contrôlé|SOP Lang, hinreichende Repräsentationen und kontrolliertes Schlussfolgern|SOP Lang, representaciones suficientes y razonamiento controlado|SOP Lang, representações suficientes e raciocínio controlado|SOP Lang, rappresentazioni sufficienti e ragionamento controllato|SOP Lang, wystarczające reprezentacje i kontrolowane rozumowanie
Comprendre comme apprendre des distinctions exécutables|Verstehen als Lernen ausführbarer Unterscheidungen|Comprender como aprender distinciones ejecutables|Compreender como aprender distinções executáveis|Comprendere come apprendere distinzioni eseguibili|Rozumienie jako uczenie się wykonywalnych rozróżnień
Les modèles linguistiques peuvent-ils reconnaître ce qu’ils n’ont jamais rencontré ?|Können Sprachmodelle erkennen, was ihnen noch nie begegnet ist?|¿Pueden los modelos lingüísticos reconocer lo que nunca han encontrado?|Podem os modelos linguísticos reconhecer o que nunca encontraram?|I modelli linguistici possono riconoscere ciò che non hanno mai incontrato?|Czy modele językowe mogą rozpoznać to, czego nigdy nie napotkały?
Ce que nous devons à un monde que nous n’avons pas choisi|Was wir einer Welt schulden, die wir nicht gewählt haben|Lo que debemos a un mundo que no elegimos|O que devemos a um mundo que não escolhemos|Ciò che dobbiamo a un mondo che non abbiamo scelto|Co jesteśmy winni światu, którego nie wybraliśmy
Droit d’auteur, marques et création à l’ère de l’IA|Urheberrecht, Marken und schöpferische Arbeit im Zeitalter der KI|Derechos de autor, marcas y creación en la era de la IA|Direitos de autor, marcas e criação na era da IA|Diritto d’autore, marchi e creazione nell’epoca dell’IA|Prawo autorskie, znaki towarowe i twórczość w epoce AI
Comment les agents personnels d’IA pourraient transformer la découverte, la confiance et le travail|Wie persönliche KI-Agenten Partnersuche, Vertrauen und Arbeit verändern könnten|Cómo los agentes personales de IA podrían transformar el descubrimiento, la confianza y el trabajo|Como os agentes pessoais de IA poderiam transformar a descoberta, a confiança e o trabalho|Come gli agenti personali di IA potrebbero trasformare la scoperta, la fiducia e il lavoro|Jak osobiści agenci AI mogliby zmienić odkrywanie, zaufanie i pracę
Bonté, pouvoir et prix de la bonne foi|Güte, Macht und der Preis der Gutgläubigkeit|Bondad, poder y precio de la buena fe|Bondade, poder e preço da boa-fé|Bontà, potere e prezzo della buona fede|Dobroć, władza i cena dobrej wiary'''
for i,(b,row) in enumerate(zip(books,subs.splitlines(),strict=True)):
 p=Path(b['workdir'])/'book/manifest.json';m=json.loads(p.read_text());m['title'].update(titlefix.get(i,{}));m['subtitle'].update(dict(zip(['fr','de','es','pt','it','pl'],row.split('|'),strict=True)));p.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n')
