from pathlib import Path
import json
rows='''Acest eseu explorează spațiul, timpul, cauzalitatea, conștiința și sensul existenței.|El pune explicațiile științifice în dialog cu întrebări filosofice.|Capitolele examinează legile naturii, emergența, emoțiile și limitele înțelegerii.|Experimentele de gândire explorează lumi simulate și forme neobișnuite de experiență.|Textul distinge dovezile empirice de conjecturi și experimente imaginare.|El întreabă cum descrierile realității modelează responsabilitatea intelectuală și morală.
Această carte examinează înțelepciunea ca problemă de judecată, educație și inteligență artificială.|Ea distinge deținerea informației de înțelegerea situațiilor și alegerea lucrurilor importante.|Exemplele pedagogice conectează reflecția filosofică, învățarea și transferul experienței.|Programul de cercetare PHRONESIS investighează distilarea judecății contextuale.|Capitolele tehnice discută reprezentări, evaluare, biasuri și experimente care ar putea infirma ipotezele programului.|Tensiunea centrală privește ceea ce păstrează compresia când o decizie depinde de context.
Acest eseu investighează lectura printre ecrane, podcasturi, filme și sisteme AI conversaționale.|El privește cărțile ca experiențe artistice, instrumente de învățare și instituții culturale.|Capitolele compară romane, manuale, articole științifice, wikiuri și formate online scurte.|Discuția examinează atenția, înțelegerea, ascultarea și atracția rezumatelor.|Ea cercetează și autoritatea ori prestigiul moral acordate adesea cărților.|Întrebarea centrală privește libertatea de a urmări un gând până la capăt.
Acest program de cercetare investighează cum regulile, stările și observatorii definesc descrierile lumilor.|El leagă întrebările filosofice despre existență de întrebări operaționale despre predicție.|Capitolele examinează complexitatea, memoria utilă, intervenția cauzală și limitele calculului.|Comparațiile între modele depind de observații explicite, bugete de resurse și criterii de echivalență.|Textul dezvoltă ipoteze, exemple și direcții pentru investigații empirice.|Problema centrală privește ceea ce pot stabili dovezile finite despre sisteme aparent similare.
Acest eseu extins explorează frumusețea corpurilor, ideilor, artei, naturii și vieții sociale.|El pune estetica filosofică în dialog cu percepția, cultura și cercetarea evoluționistă.|Capitolele discută atracția, eleganța matematică, muzica, mișcarea și spațiile cotidiene.|Alte discuții examinează autenticitatea, fragilitatea, statutul și estetica puterii.|Exemplele întreabă de ce forme diferite pot provoca experiențe la fel de convingătoare ale frumuseții.|Cartea investighează ce dezvăluie admirația și ce poate ascunde fascinația.
Acest eseu urmărește încercările repetate, de la jocurile de noroc la conversațiile cu AI.|El examinează incertitudinea, controlul perceput, rezultatele aproape reușite și promisiunea unei noi încercări.|Exemplele leagă pokerul și jocurile de strategie de descoperiri și agenți de programare.|Discuția distinge încurajarea, explicațiile convingătoare și progresul verificabil independent.|Capitolele abordează și implicarea emoțională, confirmarea și limitele dovezilor clinice.|Întrebarea recurentă privește ceea ce rămâne după entuziasm și încercări repetate.
Această investigație agnostică examinează știința, religia și pretențiile concurente la certitudine.|Douăzeci și cinci de dosare istorice explorează credințele unor gânditori influenți.|Discuția separă mărturiile biografice de argumentele științifice și filosofice.|Capitolele clarifică materialismul, ateismul, agnosticismul și limitele autorității experților.|Întrebările educaționale conectează istoria intelectuală, dovezile și responsabilitatea.|Cartea întreabă cum poate coexista incertitudinea cu diferențe semnificative între afirmații.
Acest eseu investighează libertatea prin alegere, responsabilitate și inegalitatea puterii.|El întreabă cine poate acționa și cine suportă consecințele deciziilor altora.|Argumentele filosofice întâlnesc întrebări științifice și situații sociale obișnuite.|Discuția examinează relația dintre autonomia personală și obligațiile colective.|Instituțiile și oportunitățile inegale complică explicațiile aparent simple ale alegerii individuale.|Tensiunea centrală privește condițiile și costurile unei vieți libere împreună.
Acest eseu întreabă ce sunt legile naturii și cum dobândesc explicațiile autoritate.|El conectează modelele științifice cu întrebări filosofice despre ordine și realitate.|Capitolele explorează emergența, originea regularităților și limitele înțelegerii.|Posibilitatea unei lumi simulate devine un test al descrierilor concurente.|Experimentele de gândire disting tiparele observate de afirmațiile despre mecanismele subiacente.|Întrebarea centrală privește relația dintre lume și ecuațiile care o descriu.
Acest curs dezvoltă un program de cercetare pentru raționamentul prin circuite și reprezentări suficiente.|El introduce SOP Lang alături de instrumente matematice pentru descrierea informației parțiale.|Capitolele examinează relații, ordini ale informației, interpretare abstractă și puncte fixe.|Exemplele investighează corelații pe care conexiunile individuale ale circuitului nu le pot păstra.|Discuția separă executarea, verificarea și descoperirea unei construcții utile.|Întrebarea centrală privește ceea ce trebuie să păstreze reprezentările pentru ca raționamentul să continue.
Acest curs de cercetare examinează înțelegerea ca învățare a distincțiilor executabile.|El conectează reprezentarea, interpretarea, incertitudinea și acțiunea într-o arhitectură operațională.|Capitolele matematice introduc echivalența, stările suficiente, modelele predictive și interpretarea abstractă.|Exemplele studiază contraexemple, rafinări, pierderea informației și diagnosticarea erorilor.|Programul include aplicații și experimente propuse pentru testarea afirmațiilor sale.|Întrebarea centrală privește distincțiile pe care trebuie să le păstreze un agent pentru a acționa competent.
Această monografie de cercetare investighează cum evaluează modelele lingvistice contribuțiile necunoscute.|Ea distinge noutatea de raritate, adevăr, valoare și originalitate percepută.|Capitolele examinează biasul de familiaritate, netezirea semantică și informația pierdută prin reprezentare.|Exemplele formale conectează reprezentările suficiente cu limitele evaluării ideilor noi.|Propunerile experimentale includ circuite finite, cazuri istorice de cercetare și registre de dovezi.|Tensiunea centrală privește un evaluator format de trecut care judecă abaterile de la acesta.
Acest eseu examinează responsabilitatea, de la copilărie și decizii obișnuite la instituții și creația divină.|El distinge provocarea răului, răspunderea pentru fapte și răspunsul la suferință.|Exemplele abordează sărăcia, munca, cetățenia, cunoașterea științifică și deciziile automatizate.|Argumentele filosofice întâlnesc cercetări despre capacitatea de acțiune, cooperare și comportament colectiv.|Discuția explorează obligațiile față de oamenii care nu pot răspunde pentru ei înșiși.|Întrebarea centrală privește ceea ce datorează o persoană finită unei lumi pe care nu a ales-o.
Acest curs explorează drepturile de autor, mărcile și creația în epoca inteligenței artificiale.|El compară fundamentele internaționale cu diferențele juridice dintre mai multe jurisdicții.|Rescrierea cărților și reimplementarea programelor oferă cazuri practice recurente.|Capitolele disting expresia, funcția, reputația, licențierea și domeniul public.|Discuția examinează și proveniența, aplicarea drepturilor și limitele protecției tehnice.|Întrebarea centrală privește ceea ce pot proteja creatorii când rezultate echivalente pot fi produse diferit.
Această teză de investiții explorează o rețea de agenți care reprezintă intenții personale și organizaționale.|Ea examinează dificultățile găsirii partenerilor potriviți în recrutare, investiții, cercetare și servicii locale.|Capitolele investighează calificarea reciprocă, schimbul de dovezi, negocierea și reputația contextuală.|Infrastructura propusă ridică întrebări despre confidențialitate, fraudă, descentralizare și aprobarea umană.|Discuțiile despre produs și piață abordează adoptarea inițială, cerințele operaționale și economia rețelelor.|Tensiunea centrală privește reprezentarea eficientă fără cedarea judecății sau controlului.
Acest monolog filosofic urmărește un narator fictiv care cercetează prețul bunei-credințe.|Amintirile și întâlnirile imaginate leagă bunătatea de familie, școală, muncă și credință.|Naratorul examinează dacă virtuțile care inspiră încredere pot face pe cineva mai ușor de exploatat.|Argumentele despre cooperare și competiție complică suspiciunea lui crescândă.|Scenele literare și experimentele de gândire explorează responsabilitatea, puterea și nevoia de dovezi contrare.|Cartea întreabă cât ar putea costa neîncrederea pe cineva care încă vrea să rămână bun.'''
books=json.loads(Path('.book-work/intake-20260911/books.json').read_text())
for b,line in zip(books,rows.splitlines(),strict=True):
 w=Path(b['workdir']);p=w/'book/manifest.json';m=json.loads(p.read_text());s=line.split('|');assert len(s)==6 and all(len(t.split())<=22 for t in s);m['shortDescription']['ro']=' '.join(s);m['aboutBook']['ro']=[' '.join(s[:3]),' '.join(s[3:])];p.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n');sp=w/'metadata-sentences.json';ss=json.loads(sp.read_text());ss['ro']=s;sp.write_text(json.dumps(ss,ensure_ascii=False,indent=2)+'\n')
