from pathlib import Path
import json,zipfile,base64,hashlib
p=Path(__file__).resolve().parents[1];h=lambda f:hashlib.sha256(f.read_bytes()).hexdigest();load=lambda f:json.loads((p/f).read_text());c=p/'review-revision/staged/the-museum-of-good-reasons-introduction.shf';z=zipfile.ZipFile(c);d=json.loads(z.read('film.json'));s=(p/'exports/the-museum-of-good-reasons-introduction.html').read_text();e=json.JSONDecoder().raw_decode(s[s.index('const films=')+12:])[0][0]
for a in d['assets'].values():
 if 'path' in a:a['data']=base64.b64encode(z.read(a.pop('path'))).decode()
assert d==e
qa=load('qa/browser-review.json');mat=load('qa/material-action-review.json');assert all(x['pass'] for x in qa['checks']) and not qa['jsErrors'];assert mat['pass'];assert (p/'qa/browser-review.json').stat().st_mtime>c.stat().st_mtime
v=load('work/voice-receipts.json');voice=[{'id':x['id'],'sha256':x['sha256'],'verified':h(p/'work'/x['file'])==x['sha256']} for x in v['lines']];assert all(x['verified'] for x in voice)
b=Path('docs/books/the/museum/of/good/reasons/bk-0db7c8ba679b41bb');public=b/'Animation/the-museum-of-good-reasons-introduction.shf';assert h(public)==h(p/'review-revision/previous-version/the-museum-of-good-reasons-introduction.shf')
review={'status':'Staged; awaiting independent final visual approval','candidateSha256':h(c),'durationMs':145923,'sentences':21,'maxWords':15,'scriptSha256':load('qa/sentence-policy.json')['scriptSha256'],'source':load('review-revision/source-evidence.json'),'standaloneFullFilmEquality':True,'voiceFiles':voice,'ordinaryGapsMs':1450,'sceneTransitionsMs':4000,'sharedChecksPassed':len(qa['checks']),'materialAssertionsPerTheme':len(mat['results'][0]['checks']),'fullFrames':36,'actionFrames':27,'publicUnchanged':True,'oldPublicSha256':h(public),'rootScriptReview':'Approved entire21-line script and material plan before voice.','rootFinalVisualReview':'Pending','fixes':['Source-correct brass flame/oil lamp, cup-size proportions and actual pencil contact.','Explanatory pipe behind label; no late transparent-pipe reform.','Local authored vertical route motion and foot cycles; separated visible bodies and measured following.','Supported bench lift/carry/set-down; Night-safe7metre annotation outside faces and cards.','Reader shoulders and connected bent forearm; page fold retains gutter and rest arm returns behind book.'],'audiblePlayback':False,'fullPlayback':False,'completeListeningReview':False,'browser':'Owned muted Chrome9257 with disabled background networking and external proxy/resolver restrictions.'}
(p/'qa/final-revision-review.json').write_text(json.dumps(review,indent=2,ensure_ascii=False)+'\n');print(json.dumps({k:review[k] for k in ['candidateSha256','durationMs','sentences','sharedChecksPassed','materialAssertionsPerTheme','oldPublicSha256']},indent=2))
