from pathlib import Path
import json,shutil,re
p=Path(__file__).resolve().parents[1];root=Path('docs/books/beyond/the/last/stone/bk-718ccf0885654d25');backup=p/'review-revision/previous-version';backup.mkdir(exist_ok=True)
if not (backup/'work').exists():shutil.copytree(p/'work',backup/'work');shutil.copy2(root/'Animation/beyond-the-last-stone-introduction.shf',backup/'beyond-the-last-stone-introduction.shf');shutil.copy2(root/'manifest.json',backup/'manifest.json');shutil.copy2(p/'PRODUCTION.md',backup/'PRODUCTION.md')
text=(p/'review-revision/SCRIPT-AND-ART.md').read_text();blocks=re.split(r'^## \d+\. ',text,flags=re.M)[1:];ids=['reasons-before-certainty','what-the-track-tells','stones-do-not-feed-people','when-memory-needs-marks'];sources=[[6,7],[9,10,19,20],[12,13,14],[48,49,50,52,53,54,56,57,58]];lenses=['book','content','content','reader'];arcs=['need → attentive disagreement → readiness','vigilance → action under uncertainty → attentive doubt','playful addition → practical mismatch → shared discovery','possibility → institutional questions → invitation'];states=[['curiosity','worried','curious','determined','curious'],['worried','curious','determined','reflective','curious','reflective'],['happy','surprised','curious','happy','curious'],['curious','inspired','worried','curious','inspired']];scenes=[]
for i,b in enumerate(blocks):
 lines=re.findall(r'^\d+\. (.+)$',b,re.M);title=b.splitlines()[0];scenes.append({'id':ids[i],'title':title,'lens':lenses[i],'sources':sources[i],'lines':lines,'pauseAfterMs':[1300]*(len(lines)-1)+[2200],'emotionalPlan':{'arc':arcs[i],'purpose':lines[-1],'states':states[i],'intensities':[.35 if x in ['curious','reflective']else .5 for x in states[i]],'sentenceDirection':[{'sentence':j+1,'feeling':x,'visualAction':'Concrete source action aligned to the current sentence; see approved art plan','intensity':.4}for j,x in enumerate(states[i])]},'visual':{}})
(p/'work/scenes.json').write_text(json.dumps(scenes,ensure_ascii=False,indent=2)+'\n');prod=json.loads((p/'work/production.json').read_text());prod.update(minDurationMs=120000,maxDurationMs=180000);(p/'work/production.json').write_text(json.dumps(prod,indent=2)+'\n');e=json.loads((backup/'work/editorial.json').read_text());e.update(targetMinutes=3,centralQuestion='What do signs, stories and rules allow people to know and choose when life cannot wait for certainty?',thesis='The imagined novel carries distinctions about knowing, counting and acting from a travelling group into a settlement of strangers.');e['narrativeFramework']={'why':scenes[0]['lines'][0]+' '+scenes[0]['lines'][3],'how':'Close material encounters with tracks and food-day stones give philosophical disagreement immediate consequences.','what':'Many Fires carries those questions into records, stored grain and rules between strangers.'};e['readerInvitation'].update(reasonToExist=e['narrativeFramework']['why'],readerPromise=scenes[-1]['lines'][-1],closingInvitation=scenes[-1]['lines'][-2],readerOutcomes=[scenes[-1]['lines'][-1]],contentSamples=[{'sceneId':x['id'],'readingValue':x['lines'][-1]}for x in scenes[1:3]]);e['claims']=[];e['scenePlan']=[];sections=json.loads((p/'source/sections.json').read_text());raw=(p/'source/source.txt').read_text().encode('utf-16-le')
for x in scenes:
 spans=[{'start':sections[j]['start'],'end':sections[j]['end'],'quote':raw[sections[j]['start']*2:sections[j]['end']*2].decode('utf-16-le')}for j in x['sources']];cid='claim-'+x['id'];e['claims'].append({'id':cid,'statement':' '.join(x['lines']),'kind':'source-claim','noveltyScope':'within-source','spans':spans});e['scenePlan'].append({k:x[k]for k in ['id','title','lens','emotionalPlan']}|{'claimIds':[cid]})
e['hooks']=[{'question':e['centralQuestion'],'introducedSceneId':ids[0],'status':'open-by-design','reason':'Concrete early distinctions invite following the novel into social arrangements without revealing outcomes.','sourceClaimIds':['claim-'+ids[0]]}];e['limitations']=['Imagined prehistoric philosophical fiction; no archaeological or historical reconstruction claim.','Fresh full source reads: chapters 1–5,12,13–16,24 plus front matter and all chapter headings; not a fresh whole-book reread.','Original material staging compresses the counting demonstration; six remembered waiting days are distinct from five food days.','Measured local narration; no audible background listening review.'];(p/'work/editorial.json').write_text(json.dumps(e,ensure_ascii=False,indent=2)+'\n');(p/'work/script.md').write_text('# Beyond the Last Stone\n\n'+'\n\n'.join('## '+s['title']+'\n\n'+'\n\n'.join(s['lines'])for s in scenes)+'\n');(p/'work/complete-script.txt').write_text('\n\n'.join(line for s in scenes for line in s['lines'])+'\n');print('21 approved lines applied; previous work and public preserved')
