from pathlib import Path
import json,shutil
p=Path('presentations/cant-see-the-forest-for-the-trees');r=p/'review-revision'
for f in ['art.mjs','work/scenes.json','work/editorial.json','work/voice-receipts.json']:
 d=r/'before'/f;d.parent.mkdir(parents=True,exist_ok=True)
 if not d.exists():shutil.copy2(p/f,d)
ss=json.loads((r/'before/work/scenes.json').read_text());ss[1]['lines'][2]='The book contrasts a fundamental research uncertainty with its softer description as manageable risk.';ss[2]['lines'][1]='Imagine a backup service that looks wasteful during quarters when nothing breaks.'
refs=[[4,7,8,9,10,11,26,42],[7,26],[11,16,20,22,24,28,39,42],[4,35,37,39,42]];purposes=['Establish the author personal inquiry through an editing loss, not a complete scientific theory.','Distinguish the reported authoring experience from the separate research-proposal example explicitly discussed in the source.','Enact a clearly hypothetical local-cost decision that ignores the value of an unused alternative.','Keep wider context and uncertainty visible while depicting inspection and possible correction without a demonstrated rescue.']
for i,s in enumerate(ss):
 s['sources']=refs[i];s['emotionalPlan']['purpose']=purposes[i];s['emotionalPlan']['visualActing']='Author stand-in notices a lost question, inspects two formulations, joins a local maintenance discussion and deliberately widens the field. Movement follows retained evidence, not generic pointing. Quiet uncertainty survives cautious action.'
(p/'work/scenes.json').write_text(json.dumps(ss,indent=2)+'\n');ed=json.loads((r/'before/work/editorial.json').read_text());sections=json.loads((p/'source/sections.json').read_text());b=(p/'source/source.txt').read_text().encode('utf-16-le');ed['claims']=[{'id':'claim-'+s['id'],'statement':' '.join(s['lines']),'kind':'source-claim','noveltyScope':'within-source','spans':[{'sourceId':sections[k]['id'],'start':sections[k]['start'],'end':sections[k]['end'],'quote':b[sections[k]['start']*2:sections[k]['end']*2].decode('utf-16-le')}for k in s['sources']]}for s in ss];ed['scenePlan']=[{'id':s['id'],'lens':s['lens'],'purpose':purposes[i],'emotionalPlan':s['emotionalPlan']}for i,s in enumerate(ss)];ed['narrativeFramework']['how']='Use the book own research-proposal wording contrast, then a declared hypothetical backup-service scene that separates visible upkeep from an untested future alternative.';ed['originalIllustrations']=[{'id':'author-edit','status':'Fictional author stand-in and schematic paraphrased draft, not a portrait or reconstructed actual before/after AI transcript. The source reports a loss of urgency, uncertainty and responsibility but does not provide that exact pair.','sourceBasis':['source-7','source-26']},{'id':'proposal-uncertainty','status':'Source26 explicitly discusses reframing a fundamental unknown as manageable risk; the depicted sheet is a schematic rendering of that example, not the author original manuscript edit or an empirical experiment.','sourceBasis':['source-26']},{'id':'railway-backup','status':'Original explicitly imagined rail-yard backup-service illustration, not a source-reported incident, economic estimate or maintenance instruction. No actual failure, prevented disaster or success of restored maintenance is demonstrated.','sourceBasis':['source-11','source-16','source-39','source-42']}];ed['sourceImageReview']={'count':1,'decision':'Single planet-and-forest cover inspected; no internal diagrams. Omitted because literal tree/planet scenes would obscure the writing and maintenance mechanisms.'};ed['review']={'scriptApproved':True,'reviewer':'root','sourceScope':'Fresh complete3/4/7/8/9/10/11/16/20/26/35/37/39/42; chapter-aligned opening extracts13/14/18/22/24/28/30/31/33 (13/31 complete due short length), full44-section heading map and all15chapter topics. No fresh every-word reread or bibliography validation.'};(p/'work/editorial.json').write_text(json.dumps(ed,indent=2)+'\n');q=json.loads((r/'progress.json').read_text());q.update(status='approved-production',scriptApproved=True);(r/'progress.json').write_text(json.dumps(q,indent=2)+'\n')
