import fs from 'node:fs';import {stageAuthor} from '../../../tools/shf/stage-authoring.mjs';
const file=new URL('./scenes.json',import.meta.url),scenes=JSON.parse(fs.readFileSync(file));const A='#685348',AN='#d4b4a0',B='#aa692b',BN='#ecc082';
for(const [i,s]of scenes.entries()){
 const q=stageAuthor(),{n,tint,path,text,dot,object,add,reveal,hide,move,label,link}=q;
 const weight=(id,x,y,scale=1)=>add(object(id,x,y,[tint(path('M-42 -65Q-42 -115 0 -115T42 -65',B,17),BN),tint(n('path',{d:'M-72 -64H72L105 90H-105Z',fill:A}),AN)],'A symbolic burden and polished handle; not a literal event in the source.',scale));
 const person=(id,x,identity='person-04-neutral')=>{add({id,asset:identity,x,y:480,scale:1.08,options:{color:B,dynamicExpressions:true},meaning:'A fictional participant in institutional life; identity does not encode virtue.'});for(let j=0;j<8;j++){const emotions=['curious','worried','worried','skeptical','determined','relieved','curious','neutral'];const gestures=['question','reflect','recoil','question','resolve','release','explain','reflect'];q.actions.push({actor:id,action:'character.express',beat:j+1,emotion:emotions[j],durationMs:450},{actor:id,action:'character.gesture',beat:j+1,offsetMs:650,gesture:gestures[j],durationMs:2300});}};
 const slab=(id,x,y,labelValue,w=225)=>add(object(id,x,y,[tint(n('rect',{x:-w/2,y:-43,width:w,height:86,rx:9,fill:A}),AN),tint(text(labelValue,0,10,30,'#fff'),'#30251f')],'Institutional term: '+labelValue));
 switch(i){
 case 0:weight('load',340,290,1.25);label('polish','A polished explanation',875,250,36);label('burden','An unchanged burden',875,395,36);reveal('burden',4);break;
 case 1:person('participant',220);weight('load',595,320,.8);slab('story',950,245,'Duty');label('question','Who carries the cost?',790,475,34);reveal('story',2);move('load',4,510,345);break;
 case 2:person('participant',220);person('organizer',980,'person-11-neutral');weight('shared',600,335,.65);label('cooperation','Coordination',415,180,34);label('concealment','Concealment?',850,180,34);reveal('concealment',4);break;
 case 3:add(object('altar',300,300,[tint(n('rect',{x:-115,y:-35,width:230,height:45,rx:2,fill:A}),AN),tint(n('rect',{x:-87,y:10,width:35,height:120,fill:A}),AN),tint(n('rect',{x:52,y:10,width:35,height:120,fill:A}),AN)],'Schematic altar represents sacred institutional justification.'));add(object('office',880,300,[tint(n('rect',{x:-112,y:-60,width:224,height:195,rx:8,fill:A}),AN),...[[-65,-23],[20,-23],[-65,49],[20,49]].map(([x,y])=>tint(n('rect',{x,y,width:45,height:35,fill:B}),BN))],'Office represents modern administrative justification.'));label('sacred','Sacred order',300,515,32);label('modern','Administrative order',880,515,32);reveal('office',3);break;
 case 4:person('participant',270);weight('load',610,340,.73);slab('calm',930,250,'Stay calm');label('cause','Did the cause change?',870,450,34);reveal('calm',3);reveal('cause',5);break;
 case 5:slab('ai',300,270,'AI');slab('explanation',875,205,'Explanation',290);weight('load',875,400,.6);link('generate','ai','explanation',2,'AI can generate institutional explanations; this is not proof of legitimacy.');q.objects.find(o=>o.id==='ai').visual.anchors.right=[112,0];q.objects.find(o=>o.id==='explanation').visual.anchors.left=[-145,0];label('test','What changed for the person?',600,540,32);reveal('test',6);break;
 case 6:label('enforce','Enforceable',300,250,47);label('answer','Answerable',880,250,47);add(object('difference',600,270,[text('≠',0,0,63)],'Effective control and moral defensibility differ.'));reveal('difference',2);label('view','From the weaker position',600,480,37);reveal('view',6);break;
 case 7:weight('load',265,305,.9);for(let j=0;j<3;j++){label('field'+j,['Risk','Stress','Lost opportunity'][j],855,190+j*115,33);reveal('field'+j,j+2);}label('action','Trace the transfer',600,535,36);reveal('action',5);break;
 case 8:person('participant',260);add(object('shared',720,260,[tint(n('circle',{cx:0,cy:0,r:84,fill:'none',stroke:B,'stroke-width':15}),BN),text('Promise',0,10,31)],'Shared brand promise, with independent participation.'));add(object('exit',1050,370,[tint(path('M-45 -90H45V90H-45 M-45 90V-90',A,12),AN)],'A real institutional possibility of exit, represented by a doorway.'));move('participant',5,310,480);label('right','Join · Disagree · Leave',700,520,35);reveal('right',5);break;
 case 9:for(let j=0;j<4;j++){slab('resource'+j,195+j*270,250,['Care','Time','Housing','Ecology'][j],185);reveal('resource'+j,j+1);}label('distribution','A limit does not settle its distribution',600,480,35);reveal('distribution',5);break;
 case 10:weight('before',300,285,1);weight('after',895,285,.62);label('necessary','Necessary burden',300,470,31);label('avoidable','Avoidable transfer?',895,470,31);reveal('after',2);label('inspect','Inspect the arrangement',600,550,31);reveal('inspect',5);break;
 case 11:person('participant',280);weight('load',700,300,.78);label('question','Where does the cost land?',780,495,36);reveal('question',7);break;
 }
 s.visual=q.finish('Ochre and umber burden-transfer theatre: a consistent weighted object contrasts with public explanations; expressive fictional participants react and settle.');
}
fs.writeFileSync(file,JSON.stringify(scenes,null,2)+'\n');fs.writeFileSync(new URL('./visual-bible.json',import.meta.url),JSON.stringify({direction:'Ochre and umber social theatre, polished handle and heavy load as recurring source metaphor.',cast:'person-04 is the participant; person-11 a second participant; neither identity encodes moral worth.',performance:'Curiosity, concern, skepticism, resolve, release; eight motivated sentence-level expressions and gestures in actor scenes.',sourceImages:'Only cover art present; no explanatory diagram selected.',font:'Bundled Red Hat Display/Text',limits:'Symbolic examples rather than historical reenactments or factual depictions.'},null,2));
