import assert from'node:assert/strict';import fs from'node:fs/promises';import{connect}from'./browser-session.mjs';
const base=process.env.SCRIPTA_TEST_URL||'http://127.0.0.1:8012/',collection=JSON.parse(await fs.readFile(new URL('../docs/collection.json',import.meta.url),'utf8')),book=collection.books.find(b=>b.animation),page=base+book.editions.ro.book+'?lang=ro',film=base+book.animation.page+'?lang=ro',c=await connect('about:blank'),results=[];
const instrument=`(()=>{if(location.protocol==='about:')return;window.__blocked=sessionStorage.getItem('test:animation-blocked')==='yes';window.__hidden=false;window.__starts=0;const define=customElements.define.bind(customElements);customElements.define=(name,C,...rest)=>{if(name==='shf-player'){const connected=C.prototype.connectedCallback,play=C.prototype.play;C.prototype.connectedCallback=function(){this.setMuted(true);return connected.call(this)};C.prototype.play=function(){window.__starts++;return play.call(this)}}return define(name,C,...rest)};const AC=window.AudioContext;if(AC)window.AudioContext=class extends AC{get state(){return window.__blocked?'suspended':super.state}resume(){return window.__blocked?new Promise(()=>{}):super.resume()}};const fetch=window.fetch;window.fetch=(url,...args)=>{if(String(url).endsWith('.shf')&&sessionStorage.getItem('test:animation-delay')==='yes')return new Promise(resolve=>{window.__releaseFilm=()=>resolve(fetch(url,...args))});return fetch(url,...args)}})()`;
async function navigate(url){await c.send('Page.navigate',{url});await c.wait('document.readyState==="complete"');}
async function click(selector){await c.evaluate(`document.querySelector(${JSON.stringify(selector)}).scrollIntoView({block:'center'})`);const r=await c.evaluate(`(()=>{const r=document.querySelector(${JSON.stringify(selector)}).getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}})()`);await c.send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...r});await c.send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...r});}
const state=()=>c.evaluate(`(()=>{const p=document.querySelector('shf-player');return{playing:p.playing,state:p.state,muted:p.muted,starts:window.__starts,token:sessionStorage.getItem('scriptahub:animation-start'),hash:location.hash,lang:new URL(location.href).searchParams.get('lang'),notice:p.$('notice').textContent,status:document.querySelector('[data-animation-status]').textContent}})()`);
async function ready(){await c.wait('!!document.querySelector("shf-player")?.film');}
try{
 await c.send('Page.addScriptToEvaluateOnNewDocument',{source:instrument});await c.send('Network.setCacheDisabled',{cacheDisabled:true});await c.size(1200,900);
 await navigate(film);await ready();let s=await state();assert.equal(s.playing,false);assert.equal(s.starts,0);results.push('Direct page stays paused without an audio attempt');
 await navigate(page);await c.wait('!!document.querySelector("[data-animation-link]")');await click('[data-animation-link]');await ready();await c.wait('document.querySelector("shf-player").playing');s=await state();assert(s.muted);assert.equal(s.starts,1);assert.equal(s.token,null);assert.equal(s.hash,'');assert.equal(s.lang,'ro');results.push('Trusted same-tab click starts actual narrated player once; intent consumed; language kept');
 await c.evaluate('document.querySelector("shf-player").pause()');assert.equal((await state()).playing,false);await c.send('Page.reload',{});await ready();assert.equal((await state()).starts,0);results.push('Pause works and reload does not replay consumed intent');
 await navigate(page);await c.evaluate('document.querySelector("[data-animation-link]").click()');await ready();assert.equal((await state()).starts,0);results.push('Synthetic activation does not grant an audio start');
 await navigate(page);await c.evaluate('sessionStorage.setItem("test:animation-blocked","yes")');await click('[data-animation-link]');await ready();await c.wait('window.__starts===1&&document.querySelector("shf-player").state==="paused"');s=await state();assert.equal(s.playing,false);assert.match(s.notice,/Press Play/);assert.equal(s.status,'');await c.evaluate('window.__blocked=false;sessionStorage.removeItem("test:animation-blocked");document.querySelector("shf-player").$("centerPlay").click()');await c.wait('document.querySelector("shf-player").playing');assert.equal((await state()).starts,2);await c.evaluate('document.querySelector("shf-player").pause()');results.push('Suspended autoplay unlock recovers to usable Play without false reload error; manual retry works');
 await navigate(page);await c.evaluate('sessionStorage.setItem("test:animation-delay","yes")');await click('[data-animation-link]');await c.wait('!!window.__releaseFilm');await c.evaluate(`Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});Object.defineProperty(document,'visibilityState',{configurable:true,get:()=>'hidden'});document.dispatchEvent(new Event('visibilitychange'));window.__releaseFilm()`);await ready();assert.equal((await state()).starts,0);await c.evaluate(`Object.defineProperty(document,'hidden',{configurable:true,get:()=>false});Object.defineProperty(document,'visibilityState',{configurable:true,get:()=>'visible'});document.dispatchEvent(new Event('visibilitychange'));sessionStorage.removeItem('test:animation-delay')`);assert.equal((await state()).starts,0);results.push('Becoming hidden before film readiness permanently cancels delayed start; visibility alone does not resume');
 await navigate('about:blank');await navigate(film+'#start=expired');await ready();assert.equal((await state()).starts,0);assert.equal((await state()).hash,'');results.push('A copied start fragment without its session intent remains paused');
 await navigate(page);await c.evaluate('sessionStorage.setItem("scriptahub:animation-start",JSON.stringify({token:"old",href:'+JSON.stringify(film)+',createdAt:Date.now()-20000}))');await navigate(film+'#start=old');await ready();assert.equal((await state()).starts,0);results.push('Expired same-tab intent is rejected');
 await navigate(page);await c.evaluate('sessionStorage.setItem("test:animation-delay","yes")');await click('[data-animation-link]');await c.wait('!!window.__releaseFilm');await click('[data-animation-back]');await c.wait('!!document.querySelector("[data-animation-link]")');assert.equal(await c.evaluate('!!document.querySelector("shf-player")'),false);await c.evaluate('sessionStorage.removeItem("test:animation-delay")');results.push('Back to book during loading leaves no delayed player start');
 if(c.errors.length)console.error(JSON.stringify(c.errors));assert.equal(c.errors.length,0);console.log(JSON.stringify({checks:results,errors:0,audiblePlayback:false,playerMutedBeforeLoad:true,hiddenBeforeReady:'simulated visibility event',blockedAudio:'simulated suspended resume promise'},null,2));
}finally{await c.evaluate('sessionStorage.removeItem("test:animation-blocked");sessionStorage.removeItem("test:animation-delay");sessionStorage.removeItem("scriptahub:animation-start")');await c.close()}
