import fs from 'node:fs';
const file=new URL('./scenes.json',import.meta.url); const scenes=JSON.parse(fs.readFileSync(file));
const card=(id,x,y,title,sub,fill)=>({id,asset:'custom',x,y,scale:1,meaning:`A concrete setting carried into one private decision: ${title}.`,visual:{id:'$asset',type:'g',attrs:{},children:[{id:`${id}-bg`,type:'rect',attrs:{x:-105,y:-42,width:210,height:84,rx:6,fill}},{id:`${id}-title`,type:'text',attrs:{x:0,y:-2,'font-size':23,'font-weight':600,'text-anchor':'middle',fill:'#334a54'},text:title},{id:`${id}-sub`,type:'text',attrs:{x:0,y:24,'font-size':17,'text-anchor':'middle',fill:'#334a54'},text:sub}]}});
const person=(id,x,y,coat='#73536e')=>({id,asset:id==='other'?'person-09-neutral':'person-04-neutral',x,y,scale:id==='other'?.93:1,options:{color:'#73536e',coat,dynamicExpressions:true},meaning:'A whole person making a choice in relation to others.'});
const chair=(id,x,y)=>({id,asset:'custom',x,y,scale:1,meaning:'A real seat for a supportive nearby person.',visual:{id:'$asset',type:'g',attrs:{},children:[{id:`${id}-back`,type:'rect',attrs:{x:-50,y:-100,width:100,height:100,rx:20,fill:'#efb4c3'}},{id:`${id}-legs`,type:'path',attrs:{d:'M-65 15H65M-45 15V100M45 15V100',stroke:'#73536e','stroke-width':16,fill:'none'}}]}});
const door=(id,x,y)=>({id,asset:'custom',x,y,scale:1,meaning:'An open route away from borrowed authority.',visual:{id:'$asset',type:'g',attrs:{},children:[{id:`${id}-frame`,type:'path',attrs:{d:'M-75 120V-130H75V120',stroke:'#73536e','stroke-width':15,fill:'none'}},{id:`${id}-panel`,type:'path',attrs:{d:'M-55 -110L45 -80V100L-55 120Z',fill:'#efb4c3'}},{id:`${id}-knob`,type:'circle',attrs:{cx:22,cy:15,r:7,fill:'#73536e'}}]}});
// Scene 2: several partial viewpoints become distinct everyday settings around one person.
{const s=scenes.find(x=>x.id==='scene-2'); s.visual.objects=s.visual.objects.filter(o=>!/^e[0-2]$/.test(o.id)); s.visual.objects.push(card('work-setting',280,250,'Work','task','#c9acce'),card('relationship-setting',610,250,'Relationship','seat','#efb4c3'),card('device-setting',940,250,'Digital reply','response','#b9cbdc')); s.visual.actions=s.visual.actions.filter(a=>!/^e[0-2]$/.test(a.actor)&&!/^e[0-2]$/.test(a.target)); for(const id of ['work-setting','relationship-setting','device-setting'])s.visual.actions.push({actor:id,action:'appear',beat:2,durationMs:500});}
// Scene 4: belonging is shown by an actual nearby person and a seat, then departure from checking.
{const s=scenes.find(x=>x.id==='scene-4'); s.visual.objects=[person('self',350,520),person('other',780,520,'#b46c81'),chair('seat',570,405),door('departure',1030,280)]; s.visual.actions=s.visual.actions.filter(a=>a.actor==='self'||a.actor==='other'); s.visual.actions.push({actor:'self',action:'character.express',beat:1,emotion:'curious',durationMs:500},{actor:'self',action:'character.gesture',beat:1,gesture:'question',offsetMs:500,durationMs:1500},{actor:'other',action:'appear',beat:2,durationMs:500},{actor:'seat',action:'appear',beat:2,durationMs:500},{actor:'departure',action:'appear',beat:5,durationMs:500},{actor:'self',action:'moveTo',beat:5,x:460,y:520,durationMs:900},{actor:'other',action:'moveTo',beat:5,x:780,y:520,durationMs:700});}
// Scene 8: the teacher is an imagined reference that steps aside while the chooser remains present.
{const s=scenes.find(x=>x.id==='scene-8'); s.visual.objects=[{id:'teacher',asset:'person-09-neutral',x:300,y:380,scale:.9,options:{color:'#73536e',coat:'#b46c81',dynamicExpressions:true},meaning:'An imagined teacher whose approval is no longer required.'},person('self',650,520),door('exit',980,300)]; s.visual.actions=s.visual.actions.filter(a=>a.actor==='self'||a.actor==='teacher'||a.actor==='exit'); s.visual.actions=s.visual.actions.filter(a=>a.actor!=='permission'); s.visual.actions.push({actor:'self',action:'character.gesture',beat:2,gesture:'resolve',offsetMs:500,durationMs:1500},{actor:'exit',action:'appear',beat:1,durationMs:500},{actor:'teacher',action:'moveTo',beat:3,x:220,y:380,durationMs:900},{actor:'self',action:'moveTo',beat:6,x:700,y:520,durationMs:900});}
for(const s of scenes){const ids=new Set(s.visual.objects.map(o=>o.id));s.visual.actions=s.visual.actions.filter(a=>ids.has(a.actor)&&(a.target==null||ids.has(a.target))&&a.beat<=s.lines.length);}
fs.writeFileSync(file,JSON.stringify(scenes,null,2)+'\n');
