from pathlib import Path
import json,re,shutil
w=Path('presentations/an-autopsy-of-a-digital-mind');r=w/'review-revision';old=r/'previous-version';old.mkdir(exist_ok=True)
for f in ['scenes.json','editorial.json','production.json','art.mjs','film.direction.json','voice-receipts.json','script.md']:
 d=old/f
 if not d.exists():shutil.copy2(w/'work'/f,d)
prod=json.loads((w/'work/production.json').read_text());pub=Path(prod['bookDirectory'])/'Animation'/f"{prod['id']}.shf"
if not (old/pub.name).exists():shutil.copy2(pub,old/pub.name)
t=(r/'SCRIPT-AND-ART.md').read_text();groups=re.split(r'^## \d+\. ',t,flags=re.M)[1:];ss=[];refs=[[3,4,5,6],[4,5],[48,6,9],[7,8,9]];states=[['curiosity','reflection','attention','curiosity','reflection'],['attention','concern','reflection','curiosity','attention'],['attention','tension','curiosity','reflection','concern','reflection'],['attention','reflection','curiosity','attention','curiosity']]
for i,g in enumerate(groups):
 title=g.splitlines()[0];lines=re.findall(r'^\d+\. (.+)$',g,re.M);sid=re.sub('[^a-z0-9]+','-',title.lower()).strip('-');art=g.split('Art: ',1)[1].split('## Source',1)[0].strip();gestures=[['Lean toward the exact phrase','Question the same preserved sentence','Attend to four attached tabs','Turn toward the edited manuscript','Keep volume open without certification'],['Grasp first proof corner','Set two rejected drafts on supported desk','Annotate revision request','Retain revised prose','Return attentive gaze to the reader'],['Notice the prize deadline','Attend to remembered dismissal','Put pencil against the unfinished bird wing','Keep both motives present','Pause before generalizing the phrase','Regard the example without diagnosing'],['Trace attached chapter tabs','Leave evidence judgment open','Move bookmark to Preface','Unfold context around the chosen paragraph','Keep reading with questioning attention']][i];intens=[.35,.5,.4,.3,.35,.25][:len(lines)];ep={'arc':'curiosity → attentive examination → renewed curiosity','purpose':title,'states':states[i],'intensities':intens,'gestures':gestures,'sentenceDirection':[{'sentence':n+1,'feeling':states[i][n],'visualAction':[v],'intensity':intens[n]} for n,v in enumerate(gestures)],'visualActing':art}
 ss.append({'id':sid,'title':title,'lens':'book','sources':refs[i],'lines':lines,'pauseAfterMs':[1400]*(len(lines)-1)+[2200],'emotionalPlan':ep,'visual':{'objects':[],'actions':[],'connections':[],'meaning':art}})
(w/'work/scenes.json').write_text(json.dumps(ss,indent=2)+'\n');(w/'work/script.md').write_text('# '+prod['title']+'\n\n'+'\n\n'.join('## '+s['title']+'\n\n'+'\n\n'.join(s['lines']) for s in ss)+'\n')
e=json.loads((old/'editorial.json').read_text());secs=json.loads((w/'source/sections.json').read_text());txt=(w/'source/source.txt').read_text();b=txt.encode('utf-16-le');slice16=lambda a,z:b[a*2:z*2].decode('utf-16-le');e.update(targetMinutes=2.5,centralQuestion='Why can machine prose create recognition without establishing the truth of its explanation?',thesis='The four experiments let readers examine literary force and its constructed authority while preserving the distinction between interpretation and evidence.',narrativeFramework={'why':ss[0]['lines'][1],'how':'Requested literary force and one explicitly imagined mixed-motive illustrator make the preface\u2019s question concrete.','what':'Read the four connected experiments with their context and limits.'});e['claims']=[{'id':'claim-'+s['id'],'statement':' '.join(s['lines']),'kind':'source-claim','noveltyScope':'within-source','spans':[{'sourceId':secs[k]['id'],'start':secs[k]['start'],'end':secs[k]['end'],'quote':slice16(secs[k]['start'],secs[k]['end'])} for k in s['sources']]} for s in ss];e['scenePlan']=[{'id':s['id'],'lens':s['lens'],'purpose':s['title'],'emotionalPlan':s['emotionalPlan']}for s in ss];e['hooks']=[{'question':ss[0]['lines'][1],'introducedSceneId':ss[0]['id'],'status':'open-by-design','reason':'The example demonstrates a lens and its limits without settling the book\u2019s wider arguments.','sourceClaimIds':['claim-'+ss[0]['id']]}];ri=e['readerInvitation'];ri.update(reasonToExist=' '.join(ss[0]['lines'][:2]),readerPromise=ss[-1]['lines'][-1],closingInvitation=ss[-1]['lines'][2],readerOutcomes=[ss[1]['lines'][-1],ss[2]['lines'][3],ss[-1]['lines'][3]],contentSamples=[{'sceneId':s['id'],'readingValue':s['lines'][-1]}for s in ss[1:3]]);e['originalIllustrations']=[{'id':'imagined-illustrator','status':'Explicitly imagined mixed motives within one bird illustration/prize project. No documented source case, diagnosis, prize win or healed childhood.','sourceBasis':['source-48']}];e['sourceImageReview']=json.loads((r/'source-evidence.json').read_text())['sourceImages'];e['review']={'scriptApproved':True,'independentReport':'presentations/qa/quality-review-autopsy-digital-proposal-independent.json','scope':'Exact fresh spans and image assessment in review-revision/source-evidence.json; no fresh whole-book reread.'};(w/'work/editorial.json').write_text(json.dumps(e,indent=2)+'\n');prod.update(minDurationMs=120000,maxDurationMs=210000);(w/'work/production.json').write_text(json.dumps(prod,indent=2)+'\n');p=r/'progress.json';x=json.loads(p.read_text());x.update(stage='approved-script-prepared-for-voice',next='Generate local narration, then original four-scene art; public film preserved.');p.write_text(json.dumps(x,indent=2)+'\n');print('Prepared',len(ss),'scenes',sum(len(s['lines']) for s in ss),'lines; previous version archived.')
