from pathlib import Path
import json,re,shutil
p=Path('presentations/the-smoothing');r=p/'review-revision';t=(r/'SCRIPT-AND-ART.md').read_text()
for f in ['art.mjs','work/scenes.json','work/editorial.json','work/voice-receipts.json']:
 d=r/'before'/f;d.parent.mkdir(parents=True,exist_ok=True)
 if not d.exists():shutil.copy2(p/f,d)
ss=json.loads((r/'before/work/scenes.json').read_text());groups=re.split(r'^### ',t.split('## Complete proposed speech')[1].split('## Original art plan')[0],flags=re.M)[1:];refs=[[3,7,13,16,57,59],[7,13,16,45,78],[3,13,42,43,53,57],[3,13,16,57,59,61]];purposes=['Explain why a truthful edit can conceal a consequence while retaining the book as a research proposal.','Make the original hypothetical clinic move and omitted access barrier explicit.','Compare shortened formulations against the same unchanged situation, not a universal detector.','Restore a recoverable path to detail while the underlying access problem remains unresolved.']
for i,s in enumerate(ss):
 s['lines']=re.findall(r'^\d+\. (.+)$',groups[i],re.M);s['sources']=refs[i];s['emotionalPlan']['purpose']=purposes[i];s['emotionalPlan']['visualActing']='The same visitor stays at the original access point while messages change; editor and reviewer look from the wording toward the person, inspect missing context and restore recoverable detail without resolving the journey.'
(p/'work/scenes.json').write_text(json.dumps(ss,indent=2)+'\n')
ed=json.loads((r/'before/work/editorial.json').read_text());sections=json.loads((p/'source/sections.json').read_text());source=(p/'source/source.txt').read_text();b=source.encode('utf-16-le');slice16=lambda a,z:b[a*2:z*2].decode('utf-16-le');ed['centralQuestion']='When does a truthful, easier formulation conceal a consequence that could change the reader decision?';ed['narrativeFramework']={'why':'Apparent completeness can survive the removal of affected people and consequences.','how':'One explicitly hypothetical clinic announcement omits a travel barrier while the same waiting visitor remains; shorter alternatives are compared against that unchanged situation.','what':'Read the distinction between useful and harmful compression alongside proposed instruments, falsification conditions and nonempirical literary demonstrations.'};ed['claims']=[{'id':'claim-'+s['id'],'statement':' '.join(s['lines']),'kind':'source-claim','noveltyScope':'within-source','spans':[{'sourceId':sections[k]['id'],'start':sections[k]['start'],'end':sections[k]['end'],'quote':slice16(sections[k]['start'],sections[k]['end'])}for k in s['sources']]}for s in ss];ed['scenePlan']=[{'id':s['id'],'lens':s['lens'],'purpose':purposes[i],'emotionalPlan':s['emotionalPlan']}for i,s in enumerate(ss)];ed['originalIllustrations']=[{'id':'clinic-announcement','status':'Original hypothetical clinic move and patient travel barrier, not a source-reported case, medical advice, empirical access finding or diagnosis. No reason for the barrier is invented. The same person stays after text restoration; no transport/service repair implied.','sourceBasis':['source-7','source-13','source-16','source-45','source-78']},{'id':'shortening-comparison','status':'An illustrative controlled wording comparison, not a demonstrated detector, automatic moral verdict or validated score. The source circumstances are unchanged while formulations differ.','sourceBasis':['source-42','source-43','source-53','source-57']}];ed['sourceImageReview']={'count':1,'decision':'Split-face robot cover inspected; no internal diagrams. Omitted from narrative because it does not explain the decision-relevant consequence.'};ed['review']={'scriptApproved':True,'reviewer':'root','sourceScope':'Complete3/7/13/16/41/42/43/57/59/78; chapter-aligned opening extracts11/18/22/24/26/30/45/47/49/53/55/61 and complete heading map. Single cover inspected. No fresh full-book read claimed.'};(p/'work/editorial.json').write_text(json.dumps(ed,indent=2)+'\n');d=json.loads((r/'progress.json').read_text());d.update(status='approved-production',scriptApproved=True);(r/'progress.json').write_text(json.dumps(d,indent=2)+'\n')
