from pathlib import Path
import json,shutil
p=Path(__file__).resolve().parents[1];b=Path('docs/books/the/museum/of/good/reasons/bk-0db7c8ba679b41bb');a=p/'review-revision/previous-version';a.mkdir(exist_ok=True)
assert not (a/'work').exists(),'Already applied; preserve current progress'
shutil.copytree(p/'work',a/'work')
for src,dst in [(b/'Animation/the-museum-of-good-reasons-introduction.shf',a/'the-museum-of-good-reasons-introduction.shf'),(b/'manifest.json',a/'manifest.json'),(p/'PRODUCTION.md',a/'PRODUCTION.md')]:shutil.copy2(src,dst)
draft=json.loads((p/'review-revision/proposed-scenes.json').read_text());ids=['what-the-lamp-omits','whose-route-is-shared','seven-metres-away','a-slower-kind-of-attention'];sources=[[7],[9],[7],[3,15,23,28]];arcs=['curiosity → discovery → complication → restraint','ironic curiosity → unequal freedom → held discomfort','practical improvement → recognition of loss → patient attention','broader curiosity → self-reflection → chosen reading'];states=[['curious','curious','curious','surprised','reflective','reflective'],['curious','reflective','worried','curious','reflective'],['curious','curious','sad','reflective','reflective'],['curious','reflective','curious','inspired','reflective']];scenes=[]
for i,s in enumerate(draft):
 s.update(id=ids[i],lens=['book','content','content','reader'][i],sources=sources[i],pauseAfterMs=[1300]*(len(s['lines'])-1)+[2200],emotionalPlan={'arc':arcs[i],'purpose':s['lines'][-1],'states':states[i],'intensities':[.4]*len(states[i]),'sentenceDirection':[{'sentence':j+1,'feeling':x,'intensity':.4,'visualAction':'Source-specific staged action from approved SCRIPT-AND-ART.md; each object has actual physical contact and consequence.'} for j,x in enumerate(states[i])]},visual={});scenes.append(s)
(p/'work/scenes.json').write_text(json.dumps(scenes,indent=2,ensure_ascii=False)+'\n');prod=json.loads((p/'work/production.json').read_text());prod.update(minDurationMs=120000,maxDurationMs=180000);(p/'work/production.json').write_text(json.dumps(prod,indent=2)+'\n')
e=json.loads((a/'work/editorial.json').read_text());e.update(targetMinutes=3,centralQuestion='How can explanations remain true while making a person’s loss disappear?',thesis='This philosophical novel follows a cataloguer whose material encounters reveal the framing and consequences of institutionally persuasive explanations.');e['narrativeFramework']={'why':scenes[0]['lines'][0],'how':'Mara tests labels against oil, diverging routes and a bench whose location matters beyond seating.','what':'Patient institutional mystery opens questions of care, work, public benefit and the investigator’s own use of other people.'};e['readerInvitation'].update(reasonToExist=e['centralQuestion'],readerPromise=scenes[-1]['lines'][-1],closingInvitation=scenes[-1]['lines'][-2],readerOutcomes=[scenes[-1]['lines'][-1]],contentSamples=[{'sceneId':s['id'],'readingValue':s['lines'][-1]} for s in scenes[:3]]);e['claims']=[];e['scenePlan']=[];secs=json.loads((p/'source/sections.json').read_text());raw=(p/'source/source.txt').read_text().encode('utf-16-le')
for s in scenes:
 spans=[{'start':secs[j]['start'],'end':secs[j]['end'],'quote':raw[secs[j]['start']*2:secs[j]['end']*2].decode('utf-16-le')} for j in s['sources']];cid='claim-'+s['id'];e['claims'].append({'id':cid,'statement':' '.join(s['lines']),'kind':'source-claim','noveltyScope':'within-source','spans':spans});e['scenePlan'].append({k:s[k] for k in ['id','title','lens','emotionalPlan']}|{'claimIds':[cid]})
e['hooks']=[{'question':e['centralQuestion'],'introducedSceneId':ids[0],'status':'open-by-design','reason':'Early material examples establish the reading promise; institutional and personal resolutions remain reserved.','sourceClaimIds':['claim-'+ids[0]]}];e['limitations']=['Philosophical fiction; its institution and cases are not verified real-world events.','Fresh full chapters1,2,3,4,7,9,19; prologue/epilogue, final chapter conclusion and complete chapter map; not a fresh whole-book read.','Lamp cutaway explains early concealed pipe; it is not the later transparent-pipe installation.','Bench motion and workers are conceptual reenactment of a first-chapter file, not a claimed visit by Mara.','Route traces reconstruct participants’ accounts; not an omniscient documentary view.','No audible playback or complete listening review.'];(p/'work/editorial.json').write_text(json.dumps(e,indent=2,ensure_ascii=False)+'\n');(p/'work/script.md').write_text('# The Museum of Good Reasons\n\n'+'\n\n'.join('## '+s['title']+'\n\n'+'\n\n'.join(s['lines']) for s in scenes)+'\n');(p/'work/complete-script.txt').write_text('\n\n'.join(l for s in scenes for l in s['lines'])+'\n');print('21 approved lines applied; old public/work archived')
