import fs from'node:fs';import path from'node:path';import{stageAuthor}from'../../tools/shf/stage-authoring.mjs';import{storyPerson,storyGesture}from'../../tools/shf/people-poses.mjs';const root=path.resolve('presentations/more-words-than-reality'),scenes=JSON.parse(fs.readFileSync(path.join(root,'work/scenes.json')));const C={ink:'#353344',plum:'#674668',blue:'#416b98',copper:'#b47451',mint:'#78aa94',paper:'#fff3df',gold:'#e3b556',rose:'#d28b86'};
function compose(i){const a=stageAuthor(),n=a.n;const rc=(x,y,w,h,fill,rx=0)=>n('rect',{x,y,width:w,height:h,fill,rx}),tx=(s,x,y,z=28,c=C.ink)=>a.text(s,x,y,z,c),ln=(d,c=C.ink,w=4)=>a.path(d,c,w);const put=(id,x,y,children,b=1,meaning=id,scale=1)=>{a.add(a.object(id,x,y,children,meaning,scale));a.reveal(id,b,650)},hide=(id,b)=>a.actions.push({actor:id,action:'disappear',beat:b,durationMs:160});const person=(id,x,y,coat,scale=.9)=>{storyPerson(a,id,x,y,{coat,identity:'person-11-neutral',scale});a.reveal(id,1,650);storyGesture(a,id,2,'reflect');storyGesture(a,id,4,'question')};const sheet=(w,h)=>[n('path',{d:`M${-w/2} ${-h/2}H${w/2-26}L${w/2} ${-h/2+26}V${h/2}H${-w/2}Z`,fill:C.paper}),rc(-w/2,-h/2,12,h,C.plum)];
if(i===0){
put('manuscript',448,337,[...sheet(616,328),tx('M versus baseline B',0,-111,35),tx('Claimed explanation',0,-57,27,C.plum),tx('Preserving causal relationships',0,-12,30),ln('M-252 19H250',C.copper,3),tx('Reported improvement',0,62,30,C.blue),tx('Mechanism still needs a test',0,114,28,C.plum)],1,'The source AppendixE illustrative project claims causal preservation explains improved scientific question answering; reported improvement and mechanism explanation remain different claims');
person('researcher',1074,585,C.mint,1.04);put('code',861,281,[rc(-124,-59,248,119,C.blue,4),tx('Code executed',0,-7,29,C.paper),tx('Output produced',0,34,25,C.paper)],2,'Successful execution is evidence that code ran, not that the claimed causal mechanism explains the result');
put('test-record',860,426,[...sheet(248,121),tx('Test records',0,-17,29,C.blue),tx('Same evidence?',0,28,26,C.plum)],2,'Test documents can share data and evaluator rather than provide independent corroboration');
put('review-pencil',746,484,[n('path',{d:'M-12 0L16 -106L28 -102L0 4L-10 21Z',fill:C.copper})],3,'A review annotation addresses the unverified explanatory step');

}
if(i===1){
put('experiment-head',582,211,[tx('Reported gains: M over B',0,0,35,'$ink')],1,'Three reported experiments compare the illustrative method M with baseline B; no invented magnitude or statistical result');
for(const[id,x]of[['one',271],['two',584],['three',897]])put('experiment-'+id,x,295,[rc(-121,-49,242,98,C.blue,5),tx('Experiment '+({one:'1',two:'2',three:'3'}[id]),0,-5,29,C.paper),tx('Reported gain',0,29,23,C.paper)],1,'A reported gain in one of the three source thought-experiment evaluations');
put('dependence',584,411,[ln('M-313 -65V-20H313V-65M0 -65V-20M0 -20V15',C.copper,5),rc(-431,15,862,86,C.paper,4),tx('Shared D1 split · corpus · evaluator · implementation',0,66,27)],2,'The actual shared evidence dependencies connect all three experiments; counting experiments alone does not establish independence');
put('rival',584,537,[tx('Alternative: more usable context',0,0,32,'$ink')],3,'Source rival H2 explains gains through longer effective context rather than causal-relation preservation');
for(const id of['experiment-head','experiment-one','experiment-two','experiment-three','dependence','rival'])hide(id,4);
put('equal-m',304,325,[tx('Method M',0,-100,34,'$ink'),rc(-127,-62,254,150,C.plum,4),rc(-107,-42,214,110,C.paper,2),...Array.from({length:4},(_,j)=>rc(-89+j*47,-26,34,77,C.mint,2)),tx('Same context capacity',0,124,25,'$ink')],4,'Illustrative four-cell holders represent equal context budgets, not real token counts');
put('equal-b',712,325,[tx('Baseline B',0,-100,34,'$ink'),rc(-127,-62,254,150,C.blue,4),rc(-107,-42,214,110,C.paper,2),...Array.from({length:4},(_,j)=>rc(-89+j*47,-26,34,77,C.mint,2)),tx('Same context capacity',0,124,25,'$ink')],4,'The baseline receives the same represented context capacity; equalizing context is a proposed control, not a completed causal proof');
put('independent-d2',1010,343,[...sheet(191,202),tx('D2',0,-35,43),tx('Independently',0,12,22),tx('curated',0,44,24)],4,'An independently curated second dataset is proposed alongside the existing D1 and mechanism ablation; no test outcome appears');
put('future-test',580,518,[rc(-261,-30,522,60,C.copper,5),tx('Proposed test · no result yet',0,9,29,C.paper)],5,'This comparison could challenge the explanation; source also requires mechanism ablation and additional interpretation before any stronger causal claim');
}
if(i===2){
put('inspection-sheet',574,349,[...sheet(736,362),tx('Claim record · illustrative project',0,-132,34),ln('M-316 -103H318',C.copper,3),tx('Reported improvement',-128,-59,29,C.blue),tx('M compared with B',-129,-21,25),tx('Causal preservation explains it',-89,36,29,C.plum),tx('Mechanism unconfirmed',-92,78,27,C.plum),tx('Next obligation: controlled comparison',0,142,27)],1,'The exact claim record distinguishes reported evaluation evidence from an explanatory mechanism that remains unconfirmed');
put('evidence-margin',964,277,[rc(-77,-39,154,78,C.blue,3),tx('Reported',0,8,27,C.paper)],2,'Source and execution checks can support the reported result without validating its proposed mechanism');
put('open-margin',964,424,[rc(-77,-39,154,78,C.gold,3),tx('Open',0,8,28)],2,'A separate status preserves the mechanism question, rather than promoting the whole package to demonstrated');
put('obligation',346,507,[ln('M-65 0L-34 -19L-39 -3H100',C.copper,5)],2,'Editorial annotation points to the proposed discriminating test, with no automatic pass');
person('reviewer',107,590,C.plum,.81);storyGesture(a,'reviewer',3,'explain');
put('advisory-tab',833,540,[rc(-143,-22,286,44,C.mint,4),tx('Proposed review record',0,8,24)],4,'The guardian is a research proposal and its record remains advisory; its own evaluation cannot depend on circular self-approval');
}
if(i===3){
person('research-director',168,585,C.plum,1.02);storyGesture(a,'research-director',3,'explain');
put('priority',659,215,[tx('Priority: understand the mechanism',0,0,34,'$ink')],1,'The source project constitution prioritizes mechanism understanding; another project could legitimately prioritize faster engineering transfer');
put('breadth-proposal',482,350,[...sheet(292,196),tx('Extend the benchmark',0,-51,27),tx('Same evaluator',0,-6,25),tx('Engineering transfer',0,48,24,C.blue)],1,'Source E17 extends the method to another benchmark with the same evaluator; it could suit an engineering-transfer objective');
put('mechanism-proposal',887,350,[...sheet(375,196),tx('Test the explanation',0,-51,29),tx('Equal context · D1 + D2',0,-6,25),tx('Mechanism ablation',0,48,26,C.plum)],1,'Source E21 combines controlled context, independent D2 and mechanism ablation, proposed to distinguish the rival explanations');
put('human-choice',716,480,[rc(-214,-27,428,54,C.mint,4),tx('Selected next test · still unrun',0,8,27)],3,'A person makes a conditional research-priority decision; this is not a verdict about future results or a universally best experiment');
put('chosen-mark',686,376,[n('path',{d:'M-18 -77H7V72L-6 60L-18 72Z',fill:C.copper})],3,'An editorial bookmark selects the mechanism test; it is not a green pass stamp');
put('reading-route',719,547,[tx('Taxonomy → evidence → institutions',0,0,28,'$ink')],4,'The closing route returns to the book’s chapters, evidence independence and institutional incentives rather than selling the proposed guardian as a product');
}
for(const o of a.objects.filter(o=>o.options?.rig==='character'))for(const[beat,emotion]of[[1,'curious'],[2,'skeptical'],[4,'determined'],[5,'curious']])a.actions.push({actor:o.id,action:'character.express',beat,emotion,durationMs:650});return a.finish('An editorial investigation carries one AppendixE mechanism claim through shared evidence dependence, a rival context explanation, an unrun controlled test and an explicitly human research-priority choice; no future result or automatic certification.');}
for(let i=0;i<scenes.length;i++)scenes[i].visual=compose(i);fs.writeFileSync(path.join(root,'work/scenes.json'),JSON.stringify(scenes,null,2)+'\n');
