from pathlib import Path
import json,re,shutil
p=Path('presentations/the-permission-paradox');r=p/'review-revision';t=(r/'SCRIPT-AND-ART.md').read_text().replace('Status: full proposed speech before voice; one revised sentence preserves nineteen clips.','Status: root-reviewed complete speech; two revised sentences preserve eighteen clips.').replace('An innovator may reason backward from a possible future that an institution cannot yet observe.','Imagine an inventor proposing a leak sensor whose performance has not yet been tested.').replace('A poorly evidenced prototype could justify a bounded test that changes the funding decision.','A small, controlled test could show whether that sensor detects the leak.').replace('Remaining nine-chapter overview and source-image assessment will be completed before finalization.','All nine chapter openings and the single cover were inspected; there are no internal source diagrams.');(r/'SCRIPT-AND-ART.md').write_text(t)
for f in ['art.mjs','work/scenes.json','work/editorial.json','work/voice-receipts.json']:
 d=r/'before'/f;d.parent.mkdir(parents=True,exist_ok=True)
 if not d.exists():shutil.copy2(p/f,d)
ss=json.loads((r/'before/work/scenes.json').read_text());groups=t.split('## Complete proposed speech')[1].split('## Original art plan')[0].split('### Scene ')[1:];refs=[[4,5,8,9],[5,8,9,21],[21,24,25,33],[9,21,33,46]];purposes=['Expose the evidence/resources mismatch without ranking the inventor or reviewer morally.','Make the original hypothetical sensor and its missing performance evidence explicit.','Run one bounded closed-loop test and retain an informative negative observation.','Return the same claim and negative observation to review without implying guaranteed funding or deployment.']
for i,s in enumerate(ss):
 s['lines']=re.findall(r'^\d+\. (.+)$',groups[i],re.M);s['sources']=refs[i];s['emotionalPlan']['purpose']=purposes[i];s['emotionalPlan']['visualActing']='Inventor and reviewer examine the same sensor and record; interest becomes focused concern during the missed leak, then reflective revision rather than humiliation or automatic rejection.'
(p/'work/scenes.json').write_text(json.dumps(ss,indent=2)+'\n')
ed=json.loads((r/'before/work/editorial.json').read_text());sections=json.loads((p/'source/sections.json').read_text());source=(p/'source/source.txt').read_text();b=source.encode('utf-16-le');slice16=lambda a,z:b[a*2:z*2].decode('utf-16-le');ed['centralQuestion']='How can unfamiliar proposals obtain a bounded test when evidence itself requires resources?';ed['narrativeFramework']={'why':'Past evaluative categories can miss future possibility while persuasive speculation still needs testing.','how':'An explicitly hypothetical leak sensor moves from absent evidence into one small, stoppable experiment and a retained negative result.','what':'Read the proposed conditional review, reversible inquiry and event-driven funding arrangements as connected institutional hypotheses.'};ed['claims']=[{'id':'claim-'+s['id'],'statement':' '.join(s['lines']),'kind':'source-claim','noveltyScope':'within-source','spans':[{'sourceId':sections[k]['id'],'start':sections[k]['start'],'end':sections[k]['end'],'quote':slice16(sections[k]['start'],sections[k]['end'])} for k in s['sources']]}for s in ss];ed['scenePlan']=[{'id':s['id'],'lens':s['lens'],'purpose':purposes[i],'emotionalPlan':s['emotionalPlan']}for i,s in enumerate(ss)];ed['originalIllustrations']=[{'id':'leak-sensor-bounded-test','status':'Original hypothetical acoustic leak sensor, closed tabletop loop and one missed controlled leak. Not a source case or empirical finding. One negative observation concerns one prototype/test only, does not prove every sensor fails. No people exposed, field deployment, performance number, automatic funding, or legal/medical claim.','sourceBasis':['source-8','source-21','source-24','source-25','source-33']}];ed['sourceImageReview']={'count':1,'decision':'Cover inspected; no internal diagrams. Original apparatus makes bounded test concrete without implying cover art is evidence.'};ed['review']={'scriptApproved':True,'reviewer':'root','sourceScope':'Complete4/5/8/9/21/24/25/33/46; all9 chapter openings, complete section inventory and single cover inspected. No fresh whole-book reread claimed.'};(p/'work/editorial.json').write_text(json.dumps(ed,indent=2)+'\n');d=json.loads((r/'progress.json').read_text());d.update(status='approved-production',scriptChanges=2,preservedClipsExpected=18,scriptApproved=True);(r/'progress.json').write_text(json.dumps(d,indent=2)+'\n')
p=Path('presentations/the-smoothing/review-revision/SCRIPT-AND-ART.md');p.write_text(p.read_text().replace('Consider a clinic announcement','Imagine a clinic announcement'))
