import json,pathlib
p=pathlib.Path(__file__).parent
s=json.load(open(p/'synthesis.json'))
sections=[[
([28,29,30,34,35],[1,4],'''A man sits outside a building in the cold. Nobody knows his history. Some residents blame his choices; others point to the authorities. Responsibility begins with this imaginary encounter because it exposes how much a familiar question conceals. Who caused his situation, who failed him, who can help now, and who should prevent its recurrence may be different people. The book argues that obligations should reflect a genuine ability to understand and influence events. They extend beyond blame, but their limits must protect finite lives without allowing privilege to disguise itself as helplessness.'''),
([38,39,40,41,42,43,45],[1,4],'''A bridge collapse makes the distinctions clearer. Causing an outcome, deserving criticism, owing compensation, performing an assigned role and preventing another accident require different investigations. An engineer may owe urgent inspections despite having acted properly before the collapse. Legal liability adds procedures and rules that cannot simply be inferred from moral disapproval. Separating these questions prevents both scapegoating the nearest individual and declaring everyone exempt because nobody controlled everything. Publicly accepting responsibility means little unless people can ask questions, obtain information and require changes.'''),
([47,48,49,50,51,52,53,54,57,61],[1],'''Moral luck complicates judgments: equally negligent drivers may produce radically different outcomes. Circumstances and character also have histories their bearers did not choose. Yet causal explanation does not make coercion, deliberation and deliberate avoidance of information identical. A person may owe correction without deserving the same reproach as someone who knowingly deceived. The book leaves ultimate disputes about moral truth and free will open. Its working concern is whether a demand can be justified to the people affected, rather than whether a community happens to enforce it.''')], [
([68,69,70,72,74,80,81,82,83,91,92],[1,2,3],'''The historical discussion supplies several perspectives rather than a story of inevitable moral progress. Aristotle helps illuminate choices made under unwanted pressure; traditions concerned with roles reveal how relationships create expectations. Family loyalty can support care while becoming favoritism in public office. Respect for persons challenges agreements obtained by concealing risks, while attention to consequences challenges the refuge of pure intentions. Care ethics exposes work that sustains apparently independent lives. These perspectives ask not only who acted wrongly, but whose effort makes other people's freedom possible.'''),
([96,97,100,101,102,103,104,106,107,108,110,114],[2,3],'''Responsibility develops through supported participation. A child who breaks a glass can help put things right without being branded permanently bad. Adults must make tasks possible, explain rules and accept that questioning authority may express developing judgment. Protection should allow repairable mistakes, not eliminate every opportunity to choose. Nor does parental care purchase ownership of the child's future. Gratitude and cooperation can be meaningful without an unlimited debt or a duty to guarantee another person's happiness. Maturity involves answering for actions while remaining able to receive help.'''),
([116,117,119,120,121,122,123,125,128,129,131,132,134,136],[2],'''The same distinction matters for people with cognitive difficulties or material insecurity. Worth, capacity for a particular decision and accountability for an act are separate questions. Someone who needs help understanding a contract may still know where they want to live. Someone without stable housing may lack resources an observer takes for granted, without lacking all initiative. Neither diagnosis nor poverty supplies a complete verdict. Actual alternatives and available support must be examined. Those unable to bargain, reciprocate or present an eloquent defense still have interests that others must consider.''')], [
([138,139,140,141,142,143,145,191,192,193,194],[2,3,5],'''Urgent help need not await a trial of innocence. Even a person who has behaved badly may need protection from the cold. Safety conditions remain legitimate, but they differ from tests of moral purity. The book draws on bounded housing research to question making stability a reward for already being stable, without claiming a universal policy cure. Similarly, the familiar thought experiment of rescuing a child at little cost presses the difference between not causing harm and having no duty to prevent it. Distance alone does not dissolve that demand.'''),
([195,196,197,198,199,202,205,206,207,208,211,215],[3],'''Several grounds can support helping: another's suffering, a promise, an accepted role or participation in causing harm. Repairing a concealed defect is not optional generosity. But the strongest objection to unlimited duty is that the helper's own life matters too. Special relationships may justify additional care, and repeated small requests can accumulate into an intolerable burden. Other people's failure to contribute does not automatically transfer everything to the most conscientious person. Responsibility must be assessed across time and across the people sharing a task, not request by request in isolation.'''),
([209,210,213,214,216,217,218,219,220,221],[3,4],'''Good intentions do not establish that assistance works. Its effects, alternatives and the consequences of refusing it need comparison. Recipients must be able to explain their needs, costs and objections; an apparently beneficial intervention may still be controlling or humiliating. Some fundamental protections should become predictable services rather than depend on lucky encounters with benefactors. The book does not prescribe a complete institutional arrangement. It also considers suffering beings beyond present humanity, while warning that speculative future benefits cannot provide unlimited authority to impose certain harms now.''')], [
([148,149,150,151,152,153,154,155,166,167,168],[4],'''A worker who notices a risk has duties shaped by competence, knowledge and the consequences of speaking. Following orders is no universal excuse, but saying that refusal was possible is not a complete argument either. Organizations must provide reporting routes that lead to investigation and action, with protection and real authority. Otherwise, they demand heroism from people whose decisions they constrain. The same problem appears when departments pass a complaint around without checking its outcome. Assigning a name to a task without providing the means to perform it merely prepares a scapegoat.'''),
([160,161,162,163,164,165,170,171,172,175,176,177,180,181,182,183,185,186,188],[4,5],'''Groups can obscure responsibility or make action possible. Research on bystanders must distinguish the chance that one individual helps from the chance that anyone in a crowd helps; these findings need not conflict. Explicit coordination can turn diffuse concern into identifiable tasks. Noble collective purposes can also conceal harmful means, and solidarity can protect abuse. Citizenship therefore involves limited participation and the right to challenge unjust demands. Supporting more accessible institutions need not mean confessing personal authorship of past exclusion. Present obligations and inherited blame are different questions.'''),
([225,226,229,230,231,232,233,234,239,241,242,244,246,247,249,250,251,252,253,255],[2,4,5],'''Knowledge creates specific duties without making experts universal authorities. Researchers must describe uncertainty honestly, examine how their choices affect others and resist incentives to exaggerate. They need not guarantee every future use or immediate social benefit. Automated decisions make distributed accountability especially visible: an institution, supplier and official may each point elsewhere while an affected person has no route to correction. Merely retaining a human signature is insufficient when that person lacks time, information or power. Oversight must make intervention possible. Newly discovered risks create new obligations even when earlier ignorance was reasonable.''')], [
([258,259,260,261,262,263,264,265,266,267],[1],'''The discussion of God tests the connection between power and obligation at its limit. Greater strength does not by itself make an authority legitimate, and creating a being does not obviously grant unrestricted ownership over its interests. The book distinguishes different conceptions of deity before examining their demands. A limited god, an impersonal ground of existence and an omnipotent, benevolent creator raise different questions. Divine-command accounts and appeals to a perfectly good nature require arguments about what goodness means and how claims about it can be assessed.'''),
([269,270,271,272,273,274,275,276,277,279,280,282,284,285,286,289,290],[2,5],'''Freedom, stable laws and moral development may offer reasons why some difficulty exists, but do not automatically explain every degree or distribution of suffering. Showing that a justification is possible differs from establishing it as true. The book neither proves nor disproves God's existence; it identifies an explanatory burden when unlimited knowledge, power and goodness are claimed together. Job challenges the reflex of treating suffering as proof of guilt, while later restoration need not erase earlier loss. Believers and nonbelievers can cooperate in helping through different ultimate reasons. Neither cosmic uncertainty nor criticism of providence repairs a present harm by itself.''')], [
([293,294,295,296,297,298,299,300,301,302,303],[4],'''The practical proposal is a map of judgment, not a numerical formula. It considers actual capacity, relevant knowledge, connection to harm, role, power to change conditions, costs and urgency, and the voices of those affected. No element automatically settles every case. Listening does not grant infallibility, just as assigning institutional responsibility does not necessarily reduce an individual's distinct duty. A person may need to tell the truth while an organization changes the system. These obligations are not competing slices of one quantity of guilt.'''),
([305,306,307,308,309,310,311,312,313,314,316,317,318,319,320],[4,6],'''After harm, protection, establishing facts and making reparation must be distinguished. A preventive restriction is not automatically a guilty verdict; a compelling accusation still needs evidence. Apologies gain substance through correction, and compensation cannot always undo loss. Victims do not owe forgiveness to reassure the community, while wrongdoers need not be excluded from every possible future. The aim is to make truth and repair possible without licensing repetition. Education and institutions should likewise allow decisions to be questioned and revised, although these proposals are moral arguments rather than proven interventions.''')]]
audit=dict(meaningPreserved=True,factsPreserved=True,noUnsupportedClaim=True)
def para(x):
 ids,cs,t=x
 return dict(text=t,clusterIds=[f'cluster-{c:03}' for c in cs],sourceUnitIds=[f'u{i:06}' for i in ids],audit=audit.copy())
j=dict(title='Responsibility',dek='What we owe one another when nobody controls the whole world.',sections=[dict(id=o['id'],heading=o['title'],paragraphs=[para(x) for x in ps]) for o,ps in zip(s['outline'],sections)],conclusion=[para(([324,325,326,328,329,330,331,332,333,334,335],[3,4],'''Responsibility leaves room for rest, joy and a private life valuable in itself. Yet inability to do everything is not proof that nothing falls to us. Returning to the man outside the door, the book asks for a respectful response without an invented biography or guaranteed happy ending, followed by attention to the institutions that left help to chance. The task is neither to prove universal innocence nor to become a savior, but to identify, justify and fairly share the obligations that remain.'''))],audit=dict(sameLanguage=True,centralMessagePreserved=True,coherentEssay=True,notes='Every content chapter analyzed. Research findings retain scope limits; hypothetical opening stays explicitly imaginary; no external facts added.'))
(p/'draft.json').write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n')
