import json,pathlib
p=pathlib.Path(__file__).parent
# Editorial analysis authored after reading all fourteen chapter batches.
data=[
('A justified demand between finite people requires normative argument as well as evidence.','Methodological boundary', [('Empirical descriptions and normative duties need separate justification.',1,.5,'evidence', [23,25]),('Hypothetical scenes test distinctions rather than establish frequencies.',.7,.4,'evidence',[24])], [('The bibliography supports bounded research claims.',[25,26])], [('Educational proposals are arguments, not proven interventions.',[25])]),
('Duties track actual understanding and influence, extending beyond blame while remaining limited.','Opening thesis and recurring scene',[('Causation, blame, immediate assistance, cost and prevention may concern different people.',1,.8,'distribution',[30,34]),('Limits protect conscientious people but require justification so privilege cannot feign powerlessness.',1,.9,'limits',[34])],[('The imaginary man outside a building needs no invented innocent biography.',[28,29])],[('No instrument measures blame mechanically.',[35])]),
('Responsibility is a justifiable relationship, not a single property inferred from outcomes.','Conceptual foundation',[('Causal, retrospective, role, prospective, reparative and legal responsibility differ.',1,.7,'distinctions',[39,40,41,42]),('Moral luck and causal determination complicate desert without erasing meaningful differences between coercion and deliberation.',.9,.7,'capacity',[47,48,50,51,52]),('Social existence does not establish moral legitimacy; obligations must be justified to those burdened.',1,.8,'justification',[57,58,61,62])],[('An engineer can owe new inspections without being guilty of a collapse.',[42]),('A public acceptance of responsibility matters only through explanation and correction.',[45])],[('Ultimate moral ontology remains disputed; not all ignorance is culpable.',[53,59,63])]),
('Diverse traditions illuminate character, roles, duty, consequences, power and hidden care without yielding a linear moral history.','Historical plurality',[('Choices under pressure and relational duties resist a simple free-or-forced model.',.85,.65,'capacity',[68,69,72,74]),('Respect for persons and attention to outcomes constrain each other.',.9,.6,'justification',[80,81,82,83,88,89]),('Division of labor and hidden care distribute dependence and moral burdens.',.95,.85,'distribution',[85,86,87,90,91,92,93])],[('Family loyalty can be care at home and favoritism in public selection.',[74])],[('No single genealogy or homogeneous Eastern mentality is claimed.',[67,73])]),
('Accountability varies with supported capacity, whereas moral worth does not depend on performance or reciprocity.','Agency and protection',[('Children need supported participation and explanation, not permanent shame or total exemption.',.95,.65,'capacity',[97,100,101,102,103,104]),('Care creates relationships but not ownership of another life or responsibility for every unhappiness.',.9,.8,'limits',[106,107,108,110]),('Worth, task-specific capacity and accountability are separate; inability to answer increases duties of protection.',1,.8,'vulnerability',[117,119,120,121,122])],[('Breaking a glass can lead to proportionate repair rather than a bad-child identity.',[96,101])],[('Neither diagnosis nor simple helping establishes a complete moral capacity assessment.',[98,99,123,124])]),
('Real alternatives, material conditions and institutional power must inform responsibility without erasing personal agency.','Constraint and practical help',[('Poverty changes available resources but does not define a person as blameworthy or incapable.',1,.75,'capacity',[128,129,131,132,134,136]),('Emergency assistance need not await innocence, while safety conditions and program evaluation remain legitimate.',1,.8,'vulnerability',[138,139,140,143,145]),('Employers must provide effective reporting and authority rather than rely on unprotected worker heroism.',.95,.8,'institutions',[148,149,150,151,152,154])],[('Housing First evidence supports bounded housing stability findings, not a cure for every difficulty.',[141,142])],[('Risk allegations require investigation, not an unlimited employee veto.',[153])]),
('Collective action requires identifiable responsibilities and institutions without reducing everyone to identical guilt.','Groups and citizenship',[('Individual intervention probability differs from the probability that anyone helps; coordination can clarify diffuse duties.',.95,.85,'evidence',[160,161,162,163,164,165]),('A report needs a decision and verified outcome, with resources for its owner.',1,.8,'institutions',[166,167,168]),('Present duties to repair common arrangements need not rest on inherited guilt.',1,.8,'distribution',[180,181,182,183,188])],[('Obedience can involve identification with a noble purpose, not merely blind compliance.',[170,171,172])],[('Solidarity may protect abuse; collective efficacy evidence is observational.',[175,176,177,178])]),
('There are genuine obligations to help, but personal lives, cumulative burden and recipient agency constrain their distribution.','Normative argument and strongest objection',[('Serious preventable harm at low reliable cost creates a strong demand independently of causal blame or distance.',1,.7,'help',[191,192,193,194,195]),('Special ties and cumulative demands make unlimited duty unjustifiable; others defaulting does not transfer every task to the conscientious.',1,.95,'limits',[202,205,206,207,208,211,215]),('Help should be evaluated against alternatives, respect recipients and include predictable institutional protection.',1,.85,'institutions',[209,210,213,214,216,217,218])],[('Repairing a concealed product defect is a duty, not generosity.',[196])],[('Animal and future interests are conditional arguments; speculative future benefit cannot justify unlimited present sacrifice.',[219,220])]),
('Knowledge increases specific responsibilities, while distributed technology must retain real avenues for correction.','Expertise and designed accountability',[('Research choices and honest uncertainty matter before downstream use, without requiring omnipotence or immediate utility.',.95,.7,'knowledge',[225,226,229,230,233,234]),('Expertise does not determine human worth or confer universal competence.',.9,.7,'vulnerability',[236,238,239,241,242,243,244]),('Human oversight requires time, information and authority; unknown errors still create future duties once discovered.',1,.9,'institutions',[246,247,248,249,250,251,255])],[('A signature on an algorithmic recommendation can conceal powerless oversight.',[249])],[('Ethics review is not proven long-term harm reduction; dual-use restrictions also impose costs.',[231,232,252,253,254])]),
('Claims of maximal power and goodness face an explanatory burden; neither faith nor disbelief cancels practical duties.','Testing responsibility at the limit of power',[('Creation and irresistible power do not by themselves establish unrestricted moral authority.',.95,.9,'justification',[258,260,261,262,263,265,266,267]),('Logical defense, evidential plausibility and an actual explanation differ; proposed theodicies require scrutiny.',.9,.8,'evidence',[269,270,271,272,273,274,275,276,279,280]),('Suffering does not establish deserved guilt, and later compensation need not undo loss.',.95,.9,'vulnerability',[282,283,284,285,286])],[('Job challenges convenient explanations of suffering and supports the possibility of religious protest.',[282,285])],[('The chapter neither proves nor disproves God; believers and nonbelievers can cooperate through different ultimate grounds.',[277,280,287,288,289,290])]),
('Finite responsibility needs a multidimensional map, repair and learning rather than automatic scores or limitless sacrifice.','Practical synthesis',[('Capacity, knowledge, connection, role, power, cost and affected voices must be considered without mechanical aggregation.',1,.9,'distribution',[293,294,295,296,297,298,299,300,301,302,303]),('Protection, fact-finding, repair, forgiveness, punishment and reintegration have distinct purposes.',.95,.85,'repair',[305,306,307,308,309,310,311,312,313,314]),('Learning institutions and supported education coexist with an intrinsically valuable private life.',1,.8,'limits',[316,317,318,319,320,321,322,323,324,325,326])],[('An inaccessible automated assistance application distributes distinct tasks to applicant, official, manager, researcher and citizen.',[321,322])],[('The map is not a validated score; reparations cannot erase every loss.',[294,308])]),
('One can respond to a justified immediate need without a complete biography or guaranteed happy ending.','Return to opening and practical conclusion',[('Immediate help and institutional questioning belong together.',1,.8,'help',[328,329,330,331]),('The task is to identify and fairly share finite obligations, not prove innocence or assume cosmic repair.',1,.85,'limits',[332,333,334,335])],[('Someone opens the door without certainty about the result.',[335])],[('The scene remains hypothetical and the outcome unresolved.',[328,335])]),
('Empirical findings inform moral judgment without directly determining individual blame or duty.','Evidence literacy',[('Group averages, observational associations, experiments and units of analysis must remain distinct.',.9,.65,'evidence',[337,338,339,340,341,342]),('Correct findings still need normative premises before determining treatment of people.',1,.7,'evidence',[343,344])],[('Individual helping and any-member helping answer different questions.',[342])],[('No detected difference does not establish equivalence.',[341])]),
('Precise distinctions prevent moral standing, agency and forms of duty from collapsing into blame.','Conceptual reference',[('Moral considerability is distinct from agency, and prospective duties need no prior blame.',1,.5,'distinctions',[346,347,348,349,350,351,352,353]),('An excuse reduces blame while a justification defends the act; limits of special duty and supererogation remain disputed.',.85,.5,'limits',[354,355,356,357,358,359,360,361])],[],[('Definitions describe contested families of positions rather than settling every dispute.',[346,357,359,360])])
]
def ev(items):return [{'statement':s,'sourceUnitIds':[f'u{x:06}' for x in ids]} for s,ids in items]
for n,(thesis,role,ideas,examples,quals) in enumerate(data,1):
 b=json.load(open(p/'batches'/f'batch-{n:04}.json'))
 a={'batch':b['batch'],'chapterId':b['chapterId'],'segment':b['segment'],'thesis':thesis,'role':role,'ideas':[dict(id=f'batch-{n:04}-idea-{i:03}',statement=s,centrality=c,originality=o,recurrenceCandidate=r,sourceUnitIds=[f'u{x:06}' for x in ids]) for i,(s,c,o,r,ids) in enumerate(ideas,1)],'evidenceAndExamples':ev(examples),'objectionsAndQualifications':ev(quals),'audit':{'chapterCovered':True,'meaningPreserved':True,'factsPreserved':True,'notes':'All assigned units read. Claims remain bounded; hypothetical cases are not empirical evidence.'}}
 (p/'analyses'/b['batch']).write_text(json.dumps(a,ensure_ascii=False,indent=2)+'\n')
