import fs from 'node:fs';import {vectorArt} from '../../../tools/shf/vector-story-art.mjs';
const url=new URL('./scenes.json',import.meta.url),scenes=JSON.parse(fs.readFileSync(url));const navy='#365976',navyN='#97c4e6',amber='#a56e1e',amberN='#f0c16b',cyan='#287c85',cyanN='#91d0d6',red='#a04740',redN='#e9aaa2';
for(const s of scenes){const{n,tint,path,text,dot,object}=vectorArt();const objects=[],actions=[],connections=[];const add=o=>(objects.push(o),o.id),show=(id,beat)=>actions.push({actor:id,action:'appear',beat,durationMs:1200}),hide=(id,beat)=>actions.push({actor:id,action:'disappear',beat,durationMs:800}),move=(id,beat,x,y)=>actions.push({actor:id,action:'moveTo',beat,x,y,durationMs:1800});const obj=(id,x,y,c,m,ports)=>{const o=object(id,x,y,c,m);if(ports)o.visual.anchors=ports;return add(o);};const label=(id,value,x,y,size=34)=>obj(id,x,y,[text(value,0,0,size)],value);const box=(id,x,y,value,c=navy,cn=navyN)=>obj(id,x,y,[tint(n('rect',{x:-104,y:-62,width:208,height:124,rx:10,fill:c}),cn),tint(text(value,0,10,29,'#fff'),'#14232d')],value,{left:[-108,0],right:[108,0],top:[0,-65],bottom:[0,65]});const link=(id,from,to,beat=3,anchorA='right',anchorB='left')=>{connections.push({id,from:{node:from,anchor:anchorA},to:{node:to,anchor:anchorB},color:'$ink',width:4,meaning:'Explicit dependency or process relation.'});actions.push({actor:id,action:'connection.draw',beat,durationMs:1300});};const document=(id,x,y,title,color=navy,cn=navyN)=>obj(id,x,y,[tint(n('path',{d:'M-90 -113H48L89 -72V112H-90Z',fill:color}),cn),tint(path('M48 -113V-72H89','#ffffff',3),'#182834'),tint(path('M-52 -35H49M-52 -2H49M-52 31H8','#ffffff',6),'#182834'),text(title,0,163,30)],'A named research artifact.',{left:[-93,0],right:[93,0],top:[0,-117],bottom:[0,115]});
switch(s.id){
case'the-wrong-bottleneck':for(let i=0;i<5;i++)obj('candidate-'+i,230+(i%2)*65,189+i*62,[tint(n('rect',{x:-33,y:-25,width:66,height:50,rx:5,fill:navy}),navyN)],'Multiple candidate artifacts, schematic and uncounted.');obj('funnel',624,296,[tint(n('path',{d:'M-118 -124L25 -52V52L-118 124Z',fill:amber}),amberN)],'The bottleneck of validation, not a measured throughput ratio.');box('judgment',973,295,'Judgment',cyan,cyanN);label('title','Candidates',297,532,35);show('funnel',2);break;
case'a-claim-before-evidence':document('claim',330,298,'Candidate claim');obj('question',830,286,[tint(text('?',0,35,135,amber),amberN)],'Evidence has not yet established the claim.');label('evidence','Where is the evidence?',830,482,34);show('evidence',2);break;
case'reality-can-object':box('model',303,288,'Model');box('test',874,288,'Severe test',amber,amberN);link('test-link','model','test',3);label('revision','Can this force revision?',600,500,39);show('revision',3);break;
case'cheap-generation-costly-judgment':obj('boundary',600,316,[tint(path('M0 -136V136',navy,12),navyN)],'A distinction between structural and movable limits.');label('structural','Structural limit',323,256,37);label('moveable','Engineering frontier',881,256,35);label('data','Absent information',323,385,29);label('tools','Better methods',881,385,29);show('data',3);show('tools',5);break;
case'an-evidence-bearing-object':document('record',600,284,'Research object',navy,navyN);box('data',245,220,'Evidence',cyan,cyanN);box('decisions',940,220,'Decisions',amber,amberN);box('negative',246,420,'Failed branches',red,redN);box('reasons',940,420,'Reasons',cyan,cyanN);link('evidence-link','data','record',2);link('decision-link','record','decisions',2);link('negative-link','negative','record',3);link('reasons-link','record','reasons',5);break;
case'one-change-its-consequences':box('calibration',245,310,'Calibration',amber,amberN);box('analysis',600,310,'Analysis');box('claim',956,310,'Claim',cyan,cyanN);link('depends-one','calibration','analysis',3);link('depends-two','analysis','claim',3);label('changed','A correction propagates',600,510,37);show('changed',4);break;
case'a-portfolio-not-a-pipeline':box('question',600,153,'Question',navy,navyN);for(const[i,v]of ['Rival model','Control','Replication'].entries()){box('branch-'+i,240+i*360,366,v,i===1?amber:cyan,i===1?amberN:cyanN);link('expand-'+i,'question','branch-'+i,2,'bottom','top');}label('roles','Distinct evidence roles',600,530,34);show('roles',3);break;
case'independence-is-not-a-prompt':box('claim',600,170,'Claim');box('critic',268,400,'Other code',cyan,cyanN);box('instrument',929,400,'New evidence',amber,amberN);link('check-one','claim','critic',4,'bottom','top');link('check-two','claim','instrument',4,'bottom','top');label('independence','Different failure modes',600,543,34);show('independence',3);break;
case'memory-with-reasons':document('past',290,299,'Earlier branch',navy,navyN);document('present',905,299,'Current claim',cyan,cyanN);obj('reason',600,274,[tint(text('Why?',0,20,62,amber),amberN)],'Reasons for revision are remembered between versions.');show('reason',2);label('compare','Mechanism • assumptions • evidence',600,541,31);show('compare',5);break;
case'different-kinds-of-check':obj('proof',240,290,[tint(text('∀',0,22,116,navy),navyN),text('Formal proof',0,166,33)],'Formal proof checking has stated assumptions.');obj('instrument',600,291,[tint(n('path',{d:'M-25 -110V-8L-75 97Q0 123 75 97L25 -8V-110Z',fill:cyan}),cyanN),tint(path('M-40 70H40','#fff',6),'#142830'),text('Measurement',0,165,33)],'A flask symbolizes physical measurement, not a specific experiment.');obj('community',960,300,[...[-42,42].map(x=>tint(dot(x,-26,29,amber),amberN)),tint(n('path',{d:'M-91 86Q-91 7 -42 7Q0 7 0 86M0 86Q0 7 42 7Q91 7 91 86Z',fill:amber}),amberN),text('Interpretation',0,156,33)],'Generic community silhouette as an icon for interpretive judgment, not an acting character.');show('instrument',3);show('community',4);break;
case'who-can-change-the-decision':obj('key',338,280,[tint(n('circle',{cx:-70,cy:0,r:53,fill:'none',stroke:amber,'stroke-width':20}),amberN),tint(path('M-14 0H117M70 0V47M112 0V34',amber,20),amberN)],'A key represents decision rights, not a universal administrator.');label('authority','Authority to revise',865,267,41);label('appeal','A real route of appeal',865,370,30);show('appeal',3);label('human','Purpose • limits • responsibility',600,520,32);show('human',5);break;
case'the-cost-of-being-careful':obj('balance',600,317,[tint(path('M0 91V-101M-204 -62H204',navy,15),navyN),tint(n('path',{d:'M-70 127H70L44 93H-44Z',fill:navy}),navyN),path('M-204 -62V31M204 -62V31','$ink',4),tint(n('path',{d:'M-274 33Q-204 112 -134 33Z',fill:amber}),amberN),tint(n('path',{d:'M134 33Q204 112 274 33Z',fill:cyan}),cyanN)],'A conceptual balance between assurance cost and useful correction; no numerical equilibrium claimed.');label('cost','Cost',303,192,36);label('value','Correction',911,192,36);label('minimum','Use the smallest useful structure',600,534,33);show('minimum',3);break;
case'the-research-portfolio':for(const[i,title]of ['Objects','Critics','Institutions'].entries()){document('project-'+i,265+i*335,296,title,i===1?amber:navy,i===1?amberN:navyN);if(i)show('project-'+i,3);}label('testable','Build • compare • revise',600,538,35);show('testable',5);break;
case'begin-with-the-claim':document('claim',332,298,'Begin with a claim');obj('revision',892,303,[tint(path('M-91 2A96 96 0 1 1 36 91M36 91L82 94M36 91L42 48',cyan,14),cyanN)],'A correction loop remains open to independent resistance.');label('question','What can change its mind?',827,526,35);show('question',7);break;
}
s.visual={objects,actions,connections,meaning:'Original evidence-workbench diagrams, navy, cyan and amber, with source-specific artifacts and explicit relations.'};}
fs.writeFileSync(url,JSON.stringify(scenes,null,2)+'\n');fs.writeFileSync(new URL('./visual-bible.json',import.meta.url),JSON.stringify({identity:'An evidence workbench with navy document silhouettes, amber interventions and cyan tested relations; no generic character-plus-three-props template.','sourceImages':'All 36 source images inventoried and viewed as a contact sheet. Cover omitted. Selected conceptual diagrams reauthored as large, uncluttered vectors with their relationships preserved.','adaptations':[{'scene':'the-wrong-bottleneck','source':'page-0050-image-01.png','decision':'Validation-economy sequence simplified to candidate abundance and scarce judgment, with no numeric ratio.'},{'scene':'cheap-generation-costly-judgment','source':'page-0056-image-01.png','decision':'Structural and movable limits rendered as a clear two-sided distinction.'},{'scene':'an-evidence-bearing-object','source':'page-0103-image-01.png','decision':'Research object and evidence-bearing record redrawn with only the four relevant relationships.'},{'scene':'a-portfolio-not-a-pipeline','source':'page-0113-image-01.png','decision':'Specification explosion becomes question with three rival evidence branches.'},{'scene':'different-kinds-of-check','source':'page-0191-image-01.png','decision':'Domain-sensitive autonomy expressed by three different evaluator icons, not a plot claiming measured coordinates.'}],'themes':'Filled artifacts carry dark text in Dark and white text in Color/Light; connecting ports outside silhouette edges.'},null,2));
