import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const root=path.resolve('presentations/limits-of-machine-intelligence'),r=path.join(root,'review-revision');
for(const f of ['art.mjs','work/scenes.json','work/editorial.json','work/voice-receipts.json']){const dest=path.join(r,'before',f);if(!fs.existsSync(dest)){fs.mkdirSync(path.dirname(dest),{recursive:true});fs.copyFileSync(path.join(root,f),dest);}}
const md=path.join(r,'SCRIPT-AND-ART.md');let text=fs.readFileSync(md,'utf8').replace('A proved stopping rule can cover later time without enumerating every step.','Now change the controller so its counter cannot increase beyond ten.').replace('The book compares such certificates with tests, abstractions, and observations during operation.','The book compares proofs of such limits with tests and observations during operation.');fs.writeFileSync(md,text);
const chunk=text.split('## Spoken script')[1].split('## Source and example boundaries')[0],groups=chunk.split(/^### /m).slice(1);
const refs=[[6,9],[20],[20,21,23],[23],[6,19,36]],emotions=[['curious','curious','focused','confident'],['curious','focused','confident','surprised','focused'],['concerned','focused','determined','confident'],['curious','focused','focused','determined'],['reflective','focused','reflective','curious','confident']];
const titles=groups.map(x=>x.split('\n')[0].replace(/^\d+\. /,''));
const scenes=groups.map((g,i)=>({id:'limits-r2-s'+(i+1),title:titles[i],chapter:titles[i],lens:i===0||i===4?'book':'content',sources:refs[i],lines:[...g.split('\n').slice(1).join('\n').matchAll(/^\d+\. (.+)$/gm)].map(m=>m[1]),pauseAfterMs:[],emotionalPlan:{arc:['Focused curiosity before an action','Confidence becomes a precise counterexample','Change the rule before widening the claim','Restrained practical authority','A question worth taking into reading'][i],purpose:['See the useful scope of a guarantee','Understand why a ten-step result excludes an eleventh step','Distinguish an unsafe original model from a guarded replacement','Separate patch proposal, sandbox testing and deployment','Identify the actual chapter and provisional contribution'][i],states:emotions[i],intensities:emotions[i].map(e=>e==='surprised'?.7:e==='focused'?.5:.4),visualActing:'A concrete controller and its meaningful rule change; mechanism motions settle before each mathematical claim.'}}));for(const s of scenes)s.pauseAfterMs=s.lines.map((_,j)=>j===s.lines.length-1?2000:1350);
const old=JSON.parse(fs.readFileSync(path.join(r,'before/work/editorial.json'))),sections=JSON.parse(fs.readFileSync(path.join(root,'source/sections.json'))),source=fs.readFileSync(path.join(root,'source/source.txt'),'utf8');
const e={...old,targetMinutes:2.6,centralQuestion:scenes[0].lines[0],thesis:'A correct bounded check licenses only its stated scope; this exploratory book examines the evidence required to extend that scope and authority.',narrativeFramework:{why:'Global impossibility and practical checking answer different questions.',how:'Follow a ten-step toy controller, an eleventh-step counterexample and an explicitly changed guard.',what:'Use the book’s verification distinctions to judge which action an assurance claim supports.'},readerInvitation:{...old.readerInvitation,reasonToExist:scenes[0].lines[0],readerPromise:scenes[0].lines[3],readerOutcomes:['Distinguish a bounded verification result from unbounded safety.','Identify a changed rule before claiming a wider guarantee.','Connect evidence scope with proposal, test and deployment authority.'],bookJourney:[{chapters:'Chapter 1: The Impossibility Trap and the Moving Frontier',focus:'Global limits and local certificates.'},{chapters:'Chapter 5: Practical Warrant Beyond Total Decision',focus:'Bounded model checking, invariants and operational evidence.'},{chapters:'Chapter 9: When Does an AI-Assisted Exploration Become Science?',focus:'What would justify the proposed framework beyond existing methods.'}],closingInvitation:scenes.at(-1).lines.at(-1)},claims:scenes.map(s=>({id:'claim-'+s.id,statement:s.lines.join(' '),kind:'source-claim',noveltyScope:'within-source',spans:s.sources.map(i=>({...sections[i],sourceId:sections[i].id,quote:source.slice(sections[i].start,sections[i].end)}))})),originalIllustrations:[{id:'bounded-counter',status:'Original explicitly introduced toy model; not a reported empirical study.',semantics:'Initial c=0; each transition holds or increments c; forbidden c>10. At most ten transitions preserve c<=10; eleven increments yield c=11. Scene3 explicitly changes the controller by allowing increments only while c<10, creating invariant c<=10.',sourceBasis:['source-20','source-23']}],review:{independentReviewer:'root',scriptApproved:true,conditionsApplied:['Spoken scene3 explicitly changes the controller before the wider guarantee.'],completeSourceReread:false}};
e.scenePlan=scenes.map(s=>({id:s.id,lens:s.lens,purpose:s.emotionalPlan.purpose,emotionalPlan:s.emotionalPlan}));e.hooks=[{question:scenes[0].lines[1],introducedSceneId:scenes[0].id,status:'resolved',resolvedSceneId:scenes[2].id,resolution:'An eleventh-step counterexample leaves the bounded result intact; a changed rule needs a justified invariant.',sourceClaimIds:['claim-'+scenes[1].id,'claim-'+scenes[2].id]}];e.readerInvitation.contentSamples=scenes.slice(1,4).map(s=>({sceneId:s.id,readingValue:s.emotionalPlan.purpose}));
fs.writeFileSync(path.join(root,'work/scenes.json'),JSON.stringify(scenes,null,2)+'\n');fs.writeFileSync(path.join(root,'work/editorial.json'),JSON.stringify(e,null,2)+'\n');
console.log(scenes.length+' scenes; '+scenes.reduce((n,s)=>n+s.lines.length,0)+' sentences prepared.');
