import json
from pathlib import Path
W=Path(__file__).parent

def save(n,thesis,role,ideas,evidence=(),qualifications=(),notes='Read every unit; preserve proposed versus demonstrated status.'):
 b=json.loads((W/f'batches/batch-{n:04}.json').read_text())
 def ids(nums):return [f'u{x:06}' for x in nums]
 d={'batch':b['batch'],'chapterId':b['chapterId'],'segment':b['segment'],'thesis':thesis,'role':role,'ideas':[{'id':f'batch-{n:04}-idea-{i:03}','statement':s,'centrality':c,'originality':o,'recurrenceCandidate':r,'sourceUnitIds':ids(u)} for i,(s,c,o,r,u) in enumerate(ideas,1)],'evidenceAndExamples':[{'statement':s,'sourceUnitIds':ids(u)} for s,u in evidence],'objectionsAndQualifications':[{'statement':s,'sourceUnitIds':ids(u)} for s,u in qualifications],'audit':{'chapterCovered':True,'meaningPreserved':True,'factsPreserved':True,'notes':notes}}
 (W/'analyses').mkdir(exist_ok=True);(W/'analyses'/b['batch']).write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')

save(1,'A continued contents page, without substantive argument.','Navigation only; exclude from final idea ranking.',[],notes='All entries read. Duplicate contents continuation missed by automatic classifier; intentionally no ideas and empty final chapter coverage.')
save(2,'Understanding research should investigate which distinctions must be preserved for subsequent reasoning.','Defines scope, claim types and limits.',[
 ('Execution, discovery and justification are distinct challenges; the working thesis concerns learning relevant distinctions.',1,.9,'sufficient interfaces',[54,55,65]),
 ('SOP Lang is a proposed conceptual research architecture, not a validated general understanding system.',1,.6,'bounded claims',[56,57,63,64]),
 ('Exact equivalence must be distinguished from sound approximation.',.95,.5,'guarantee types',[61])],qualifications=[('Finite numerical observations do not establish natural-language or general-system performance; AI agreement is not independent validation.',[57,64])])
save(3,'Explicit reasoning circuits become useful when their interfaces preserve relevant semantic distinctions, but explicitness alone establishes neither discovery efficiency nor worldly truth.','Chapters 1–4 establish operational understanding, circuit objects and compositional contracts.',[
 ('Histories may share continuation only when relevant future observations cannot distinguish them.',1,.9,'sufficient interfaces',[82]),
 ('Domain-relative understanding includes coherent answers, missing-information diagnosis and revision under changed premises.',.95,.7,'operational understanding',[93,94,95,101]),
 ('Source statements, interpretations, world claims and kinds of uncertainty must remain distinguishable.',1,.8,'epistemic provenance',[97,98,99]),
 ('Circuit source, executed instance and materialized content are distinct; SSA names do not remove loops or effects.',.8,.5,'circuit architecture',[106,108,110,111,112,114,115,116]),
 ('Semantic contracts support composition, but compatibility does not select a useful construction or supply missing context.',.95,.7,'compositional contracts',[123,124,125,128,129,134,135,136])],evidence=[('Warehouse quantities require temporal and availability interpretations before arithmetic; conditional answers may be appropriate.',[71,72]),('Lending and permanent transfer can agree on possession while differing in ownership.',[95]),('An entire retained execution can be too expensive or unusable for human audit.',[120])],qualifications=[('Methodological circuit models do not imply that reality itself is a circuit or solve consciousness.',[89,90,91]),('DisCoCirc is an acknowledged precedent, not an invention claimed here.',[131,132]),('Accepted circuits hide rejected search paths; both discovery and result costs matter.',[76,77,102])])
save(4,'Partial information can support disciplined reasoning when possibility, necessity, approximation and relational dependence remain explicit.','Chapters 5–8 establish mathematical foundations.',[
 ('Possibility requires one compatible world; entailment requires all; incompatible premises must be reported rather than treated as every answer succeeding.',.95,.6,'guarantee types',[150,151,152,154,155,156]),
 ('Refinement narrows possibilities, while revision can restore possibilities after a false premise is withdrawn; provenance enables retraction.',.95,.7,'epistemic provenance',[162,164,175,178,179,180]),
 ('Fixed points indicate closure under available propagators, not complete solutions; termination relies on finite monotone fair refinement or lossy widening.',.8,.5,'bounded claims',[171,172,174,175,176]),
 ('Sound overapproximation preserves actual possibilities but may admit spurious ones; exact compositional summaries require stronger compatibility.',1,.7,'guarantee types',[188,189,190,191,193,194,195,200,202,203,204,205]),
 ('Relations among frontier values can carry decisive information that individual descriptions lose; compact algebra may preserve it without enumeration.',1,.9,'relational frontier',[197,198,199,211,212,215,216,217,219,220,221]),
 ('Vector size or symbol length alone hides interpreter, retrieval and interference costs.',.8,.6,'representation costs',[223,224,225])],evidence=[('Parity suffices for addition parity but not size comparisons.',[184,185,203]),('Knowing y equals x makes their difference zero; independent intervals forget this.',[197,198]),('Binary equality constraints can expose a contradiction through linear elimination instead of all assignments.',[215,216,217])],qualifications=[('A maximally broad sound description can be useless; measure discrimination and false alarms.',[193,194]),('Interfaces may themselves grow rapidly and require different algebras for different domains.',[195,199,208,220])])
save(5,'Search can merge histories with identical relevant futures when a sufficient interface composes exactly, but finding economical interfaces is the open research challenge.','Chapters 9–13 give the central proposition, algorithms and counterexample mechanisms.',[
 ('Execution and verification do not guarantee efficient discovery; account for libraries, representation, preprocessing and checking.',.95,.6,'representation costs',[231,232,233,235,237,239,240,241,243,244]),
 ('Continuation equivalence is relative to permitted observations, including provenance or effects; similarity on samples is not proof.',1,.8,'sufficient interfaces',[248,249,252,253,254,255,258,259,261,262,263,265,266,267]),
 ('If summary updates commute with every admissible operation and preserve final observation, equal summaries support exact continuation by induction.',1,.9,'sufficient interfaces',[270,271,272,273,274,275,276,277]),
 ('Layered merging bounds extension evaluations by stages times distinct summaries times branching, with representation, budget and arithmetic costs additional.',.95,.7,'representation costs',[279,280,281,282,284,285,286]),
 ('Dynamic programming, knowledge compilation, small separators and algebraic structure exploit conditional structure; e-graph equality differs from alternative interpretation.',.9,.6,'relational frontier',[293,294,296,297,298,300,301,302,304,305,306,308,309]),
 ('Backward requirements filter candidates; abstract overlap is not realizability. CEGAR repairs abstractions; CEGIS repairs candidate programs.',.9,.7,'counterexample learning',[312,313,315,316,317,319,320,321,323,324]),
 ('Learned interfaces should survive distinguishing continuations and transfer beyond examples, rather than accumulate exceptions; budget-limited failure to refute is not proof.',1,1,'counterexample learning',[288,289,290,326,327,328])],evidence=[('Sum requires a partial sum, mean also a count, while median generally needs more.',[258]),('Affine coefficients remain sufficient under affine operations but not squaring.',[275,276,277]),('The x/x rewrite requires nonzero input under suitable semantics.',[306])],qualifications=[('Neither a huge number of summaries nor expensive discovery yields economical compression automatically.',[281,282,290]),('Underlying dynamic programming and congruence mathematics is acknowledged prior work.',[288]),('Misinterpreted text can leave both abstraction and program verification solving the wrong problem.',[324])])
save(6,'Language reasoning must preserve epistemic context, alternatives and relations; task-specific compression should remain revisable from richer memory.','Chapters 14–18 apply the formal principles to language, neural representations and prediction.',[
 ('Texts propose interpretations rather than validated facts; events, roles, temporal contexts and provenance must retain separate statuses.',1,.8,'epistemic provenance',[334,335,336,338,339,340,342,343,344,350,351]),
 ('Packed alternatives share common reasoning without premature pronoun resolution; dependencies must prevent mixing incompatible worlds.',.95,.85,'relational frontier',[354,355,356,358,359,360,370,371]),
 ('Semirings distinguish alternatives and composition; derivation counts, world counts and probabilities differ, and provenance retains alternative support.',.85,.7,'epistemic provenance',[362,363,364,366,367,368]),
 ('Time, persistence, explicit negation, quantifier scope, reported beliefs and causal intervention require their own contracts.',.95,.7,'compositional contracts',[374,375,376,378,379,380,382,383,384,386,387,389,390,391]),
 ('Symbolic, neural and distributed are not exclusive camps; compare exactness, explicitness and representation axes with fixed memory and error budgets.',.85,.7,'representation costs',[394,395,396,398,399,400,402,403,404,407,408,410,411]),
 ('Exact computational sufficiency, sound approximation and predictive sufficiency differ; bottleneck compression only preserves specified targets under assumptions.',.95,.7,'guarantee types',[414,415,416,418,419,420,422,423,424,425]),
 ('Preserve sources and richer memory separately from question-specific views so rare exceptions and new questions can reopen discarded distinctions.',1,.95,'revisable memory',[427,428,429,431,432])],evidence=[('Possession after a transfer does not establish ownership or that a key was used to enter a library.',[338,339,340]),('The ambiguous pronoun can be irrelevant to possession yet essential to identifying who leaves.',[354,355]),('Withdrawing one source need not withdraw a conclusion if independent support remains.',[366,368])],qualifications=[('No complete verifier exists for every open-language claim; partial checks need explicit limits.',[408]),('Statistical prediction does not establish intervention effects.',[389,390,391,420]),('Shared grammars do not guarantee cheap unrestricted semantics.',[359,371])])
save(7,'SOP Lang proposes operational, semantic and epistemic interfaces that organize shared search, revision and auditable answers; finite models illustrate mechanisms without validating the full architecture.','Chapters 19–23 integrate the design, a worked question and carefully bounded observations.',[
 ('Interfaces expose content kind, guarantee and dependencies through shared references; operational validity cannot launder uncertain premises into certainty.',1,.8,'circuit architecture',[438,439,440,442,443,444,446,447,448]),
 ('The expander joins forward possibilities and backward requirements in a shared graph, filtering cheaply and checking acceptance more strongly.',.95,.8,'circuit architecture',[450,451,452,454,455,456]),
 ('The key example illustrates question-relative ambiguity, abstention and local retraction when a transfer is corrected to showing.',1,.9,'revisable memory',[459,460,461,463,464,465,467,468,469,471,472,475,476,477,479,480,482,483]),
 ('Parameter learning, circuit learning and representation learning differ; reusable abstractions must transfer and their library, exception and human costs remain visible.',.95,.8,'counterexample learning',[486,487,488,490,491,492,494,495,496,498,499,500,502,503,504]),
 ('Short justification, diagnostic alternatives and reproducible computation serve distinct audit needs; value provenance differs from search-decision provenance.',.9,.8,'epistemic provenance',[507,508,509,511,512,513,515,516,517,519,520,521]),
 ('Finite affine models demonstrate exact merging with supplied coefficients, not learned representations; counts concern extensions rather than measured full speedups.',.95,.7,'bounded experiments',[524,525,527,528,529,531,532,533,535,536]),
 ('Parity constraint experiments show the inadequacy of individual domains and value of suitable relational algebra, without disproving all local propagation.',.95,.8,'relational frontier',[538,539,540,542,543])],evidence=[('At sixteen stages, 65 536 histories corresponded to 430 final functions and 4 794 forward extensions; modulus and representation were supplied.',[527,528,531,532,533]),('The key example must not invent who returned the key from a later observation.',[469,476]),('A corrected transfer should invalidate only dependent conclusions while preserving independent information.',[479,480,515])],qualifications=[('The worked language example is proposed behavior, not prototype achievement.',[460,461]),('Finite results leave economical autonomous interface discovery and language transfer unproven.',[525,533,543]),('Formal verification of a plan does not authorize its external effects.',[517])])
save(8,'The architecture becomes a research program through separately falsifiable claims, strong comparisons, staged learning and explicit failures.','Chapters 24–28 specify hypotheses, experiments, objections and progression.',[
 ('Exact merging, useful relations, selective ambiguity, interface transfer, learned selection and diagnostic benefit require separate tests and failure criteria.',1,.8,'bounded experiments',[549,550,552,553,554,556,557,559,560,562,563,565,566,568,569]),
 ('Formal experiments should vary state size, representation richness, graph topology and algebra independently, using adversarial continuations and full amortized costs.',.95,.8,'bounded experiments',[575,576,577,579,580,581,583,584,585,587,588,589,591,592,593,595,596]),
 ('Language experiments separate interpretation from reasoning, vary minimal pairs and new compositions, test rare exceptions, and report coverage, abstention and proof validity.',1,.85,'bounded experiments',[599,600,601,603,604,605,607,608,609,611,612,613,615,616,617,619,620]),
 ('Known dynamic programming, hidden primitives, large interfaces and difficult semantic verification are substantive objections; local guarantees cannot be certified global truth.',.95,.7,'bounded claims',[623,624,626,627,629,630,632,633,635,636,638,639,641,642]),
 ('Progress proceeds from exact finite models through adaptive interfaces, revisable controlled language and transfer to independent real-document evaluation.',.95,.8,'counterexample learning',[645,646,648,649,651,652,654,655,657,658]),
 ('Understanding as preserving relevant distinctions remains a philosophical hypothesis; negative results and independent criticism can improve it.',1,.8,'bounded claims',[571,572,660,661,663,664,665,666,667])],evidence=[('Changing gave to showed or all to some tests meaning-sensitive responses; consistent renaming should not.',[604,605]),('Holding the verifier fixed isolates the effect of learned candidate selection.',[565,566,615,616]),('Diagnostic benefit requires independent evaluators, not confidence in attractive explanations.',[568,569,641,642])],qualifications=[('Formal correctness may be practically useless, and exhaustive future questions may prevent compression.',[629,630,638]),('Multiple outputs from the same model type are not independent confirmation.',[660,661])])
save(9,'The workshop makes exactness, soundness, relational dependence and research accountability explicit through proofs and counterexamples.','Appendices reinforce the central argument and prescribe auditable reporting.',[
 ('Exact continuation depends on closed summary updates, observable results and preserved admissibility; the proof does not establish small or learnable summaries.',1,.7,'sufficient interfaces',[673,674,675,676,677]),
 ('Sound abstraction supports rejecting impossible branches, while accepting a candidate requires a concrete witness or stronger representation.',.95,.7,'guarantee types',[679,680,681,682,683,700,701]),
 ('Independent projections may invent combinations; a relational vocabulary can preserve the lost dependency compactly.',.95,.7,'relational frontier',[685,686,687,688]),
 ('Exercises distinguish semantic types, question-relative sufficiency, provenance, empirical samples, budget failure and causal intervention.',.9,.6,'compositional contracts',[692,695,698,704,707,710,713,716,719,722,725,728,731,734]),
 ('Publishable results must disclose domain, supplied and learned components, proof level, complete cost, failures and possible refutations.',.95,.8,'bounded experiments',[780,782,784,786,788,790])],evidence=[('A sum needs a count to determine a mean; neither determines whether all elements were equal.',[692,695]),('Two articles copying one report are not independent confirmations.',[712,713]),('Accumulating exceptions may be memory rather than structural learning.',[724,725])],qualifications=[('A selection policy using hidden state is not covered automatically by the summary induction.',[675,676]),('A certificate does not certify the external truth of premises.',[746])])
